### ISSUE TITLE
Socnetsim difficult to setup

### ISSUE THREAD

**Issue by phaj19** [matsim-org/matsim-libs#1094]
Hi, I have been struggling to set up socnetsim for almost a week and therefore I would appreciate some guidance.
Setup:
RunExampleSocialSimulation.java
basic Sioux falls example - Note: some files that were required in the provided config.xml are missing in Github like facilities.xml
(could somebody fix that?)
my fix: I used those from some other Sioux falls case which I found.

Matsim version in Maven:
13.0-SNAPSHOT
socnetsim - tested 13.0-SNAPSHOT and then 12.0-2019w45-SBB with patching of the incompatibilities (like OptionalTime)

I was able to patch most of the problems up to this point:
2020-08-03T17:53:58,834 ERROR AbstractMultithreadedGenericStrategyModule$ExceptionHandler:135 Thread SynchronizeCoTravelerPlansModule_0 died with exception. Will stop after all threads finished.
java.lang.RuntimeException: exception when handling JointPlan: plans=10132_4: 1; 41069_2: 1; 
	at org.matsim.contrib.socnetsim.framework.replanning.modules.AbstractMultithreadedGenericStrategyModule$PlanRunnable.run(AbstractMultithreadedGenericStrategyModule.java:123) ~[socnetsim-12.0-2019w45-SBB.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: Problem analyzing joint plan JointPlan: plans=10132_4: 1; 41069_2: 1; 
	at org.matsim.contrib.socnetsim.jointtrips.JointTravelUtils.analyseJointTravel(JointTravelUtils.java:58) ~[socnetsim-12.0-2019w45-SBB.jar:?]
	at org.matsim.contrib.socnetsim.jointtrips.replanning.modules.SynchronizeCoTravelerPlansAlgorithm.run(SynchronizeCoTravelerPlansAlgorithm.java:61) ~[classes/:?]
	at org.matsim.contrib.socnetsim.jointtrips.replanning.modules.SynchronizeCoTravelerPlansAlgorithm.run(SynchronizeCoTravelerPlansAlgorithm.java:1) ~[classes/:?]
	at org.matsim.contrib.socnetsim.framework.replanning.modules.AbstractMultithreadedGenericStrategyModule$PlanRunnable.run(AbstractMultithreadedGenericStrategyModule.java:120) ~[socnetsim-12.0-2019w45-SBB.jar:?]
	... 1 more
Caused by: java.lang.RuntimeException: no valid trip found for passenger 10132_4 in driver trip [DriverTrip: driverId=41069_2, driverTrip=[leg [mode=car_driver][depTime=18:08:24][travTime=00:05:19][arrTime=18:13:43][route=[DriverRoute: delegate= startLinkId=29_1 endLinkId=18_4 travTime=OptionalTime[319.18486974426924] dist=6357.867213082338 linkIds=[29_2, 29_3, 29_4, 50_1, 50_2, 50_3, 54_1, 54_2, 54_3, 54_4, 18_1, 18_2, 18_3] travelCost=53.552128145983005; passengers=[10132_4]]]], passengerOrigins={10132_4=29_1}, passengerDestinations={10132_4=18_4}]
	at org.matsim.contrib.socnetsim.jointtrips.JointTravelUtils.getNextPassengerTrip(JointTravelUtils.java:118) ~[socnetsim-12.0-2019w45-SBB.jar:?]
	at org.matsim.contrib.socnetsim.jointtrips.JointTravelUtils.reconstructJointTrips(JointTravelUtils.java:75) ~[socnetsim-12.0-2019w45-SBB.jar:?]
	at org.matsim.contrib.socnetsim.jointtrips.JointTravelUtils.analyseJointTravel(JointTravelUtils.java:53) ~[socnetsim-12.0-2019w45-SBB.jar:?]
	at org.matsim.contrib.socnetsim.jointtrips.replanning.modules.SynchronizeCoTravelerPlansAlgorithm.run(SynchronizeCoTravelerPlansAlgorithm.java:61) ~[classes/:?]
	at org.matsim.contrib.socnetsim.jointtrips.replanning.modules.SynchronizeCoTravelerPlansAlgorithm.run(SynchronizeCoTravelerPlansAlgorithm.java:1) ~[classes/:?]
	at org.matsim.contrib.socnetsim.framework.replanning.modules.AbstractMultithreadedGenericStrategyModule$PlanRunnable.run(AbstractMultithreadedGenericStrategyModule.java:120) ~[socnetsim-12.0-2019w45-SBB.jar:?]
	... 1 more
NOTE: row numbers might not match perfectly due to some hotfixes (mostly turning OptionalTime to double)

And now I can not figure out any fix. I reach the same dead end from both versions I tried. 
In one of my investigations it turned out there was a mismatch between route.getStartLinkId() and originId inside getNextPassengerTrip() function, perhaps that helps.

**Comment by rewertvsp** [comment]
I think we can close this thread now, as there have been no further questions in recent years. :)
