### ISSUE TITLE
Carsharing: Beginner Questions

### ISSUE THREAD

**Issue by RealInfinity** [matsim-org/matsim-libs#1105]
Hello,

I'm trying to integrate Carsharing into an existing MATSim scenario and adapted the `RunMatsim.java` and `config.xml` according to the  `org.matsim.contrib.carsharing.runExample`. To keep it simple I started with free-floating sharing only and 70 cars available for everyone. If you would like to see my code and inputs, I think that I could share it via e-mail.

Unfortunately, I get an error when I try to use the `RandomTripToCarsharingStrategy`. Do you have an explaination for it? 

```
2020-08-03T20:28:37,160 ERROR SimStepParallelEventsManagerImpl$ExceptionHandler:420 Thread class org.matsim.core.events.SimStepParallelEventsManagerImpl$ProcessEventsRunnable0 died with exception while handling events.
java.lang.NullPointerException: null
	at org.matsim.contrib.carsharing.events.handlers.PersonArrivalDepartureHandler.handleEvent(PersonArrivalDepartureHandler.java:113) ~[carsharing-12.0.jar:?]
	at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:278) ~[matsim-12.0.jar:?]
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:139) ~[matsim-12.0.jar:?]
	at org.matsim.core.events.SimStepParallelEventsManagerImpl$ProcessEventsRunnable.run(SimStepParallelEventsManagerImpl.java:330) ~[matsim-12.0.jar:?]
```

When I run it just with the `CarsharingSubtourModeChoiceStrategy` it seems to work but no Carsharing trips appear in the modestatistics. 
![image](https://user-images.githubusercontent.com/63114439/89734746-46555580-da5e-11ea-93de-9fd40b925676.png)

This might indicate that it's just not profitable with the current parameters so I thought it would be an idea to change the values in the CostCalculationExample.java. Can you tell me how I do that? (...because there is currently no carsharing folder in Eclipse?) 

The last question might be a kinda stupid one, but although I've already invested several weeks in reading and trying out things, I still feel like a very beginner sometimes regarding MATSim, Java, Eclipse etc. :|

I hope you can help me!
Many thanks in advance!!

**Comment by RealInfinity** [comment]
_Update_

I've found a solution for the second part of my question (see below if any other beginner is interested). 
Unfortunately the main issue (NullPointerExeption) still remains :/

---

One can remove carsharing from the pom.xml, import the carsharing folder (from the contrib directory) to Eclipse instead and then add a path...

![image](https://user-images.githubusercontent.com/63114439/90336852-d0616900-dfde-11ea-961f-41d7028979ae.png)

After doing so it looks like that: "matsim-example-project" > "Properties" >

![image](https://user-images.githubusercontent.com/63114439/90336927-4b2a8400-dfdf-11ea-96b0-c1441354041b.png)

**Comment by RealInfinity** [comment]
_Update_

Using the `CarsharingSubtourModeChoiceStrategy` only does not lead to carsharing trips. 
(Screenshots from the carsharing runExample)

![image](https://user-images.githubusercontent.com/63114439/90340919-9e123480-dffb-11ea-9215-637d0fd7ff95.png)
![image](https://user-images.githubusercontent.com/63114439/90340926-b2eec800-dffb-11ea-8786-3f3645bb8ea1.png)
