### ISSUE TITLE
Berlin example may need fixes to run with MATSim 12.0

### ISSUE THREAD

**Issue by pastelmind** [matsim-org/matsim-libs#1181]
I'm using the standalone version of MATSim 12.0 from [here](https://www.matsim.org/downloads/). The ZIP file contains many examples, but I'm having problems with several of them.

I tried to run `examples/berlin/config.xml`, but the simulation fails with the following error message:

```
2020-09-27T16:29:37,849 ERROR SimStepParallelEventsManagerImpl$ExceptionHandler:420 Thread class org.matsim.core.events.SimStepParallelEventsManagerImpl$ProcessEventsRunnable0 died with exception while handling events.
java.lang.RuntimeException: just encountered mode for which no scoring parameters are defined: ride
	at org.matsim.core.scoring.functions.CharyparNagelLegScoring.calcLegScore(CharyparNagelLegScoring.java:99) ~[matsim-12.0.jar:?]
	at org.matsim.core.scoring.functions.CharyparNagelLegScoring.handleLeg(CharyparNagelLegScoring.java:177) ~[matsim-12.0.jar:?]
	at org.matsim.core.scoring.SumScoringFunction.handleLeg(SumScoringFunction.java:109) ~[matsim-12.0.jar:?]
	at org.matsim.core.scoring.ScoringFunctionsForPopulation.handleLeg(ScoringFunctionsForPopulation.java:175) ~[matsim-12.0.jar:?]
	at org.matsim.core.scoring.EventsToLegs.handleEvent(EventsToLegs.java:349) ~[matsim-12.0.jar:?]
	at org.matsim.core.scoring.EventsToLegsAndActivities.handleEvent(EventsToLegsAndActivities.java:68) ~[matsim-12.0.jar:?]
	at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:278) ~[matsim-12.0.jar:?]
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:139) ~[matsim-12.0.jar:?]
	at org.matsim.core.events.SimStepParallelEventsManagerImpl$ProcessEventsRunnable.run(SimStepParallelEventsManagerImpl.java:330) ~[matsim-12.0.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

I "fixed" `examples/berlin/config.xml` by adding the following lines:

```xml
	<module name="planCalcScore">
		<!-- snip -->

		<parameterset type="scoringParameters">
			<!-- snip -->

			<!-- This is what I added -->
			<parameterset type="modeParams">
				<param name="mode" value="ride"/>
			</parameterset>
			<parameterset type="modeParams">
				<param name="mode" value="walk"/>
			</parameterset>

		</parameterset>
	</module>
```

Now the simulation finishes properly. However, I don't quite understand what this fix does, or why it was needed. Any advice or insights would be welcome.

**Comment by mrieser** [comment]
Thanks for reporting this! I'll fix this so that in future releases, it should hopefully work out of the box.

> However, I don't quite understand what this fix does, or why it was needed. Any advice or insights would be welcome.

Short answer: The plans used for the simulation (`examples/berlin/plans_hwh_1pct.xml.gz`) includes legs with modes `ride` and `walk`. After these legs are executed by the mobility simulation, they need to be scored, but there are no scoring parameters defined for those modes in the `config.xml`. By defining them as you did, they will be created and use a default value for the `marginalUtilityOfTraveling_util_hr`, so it will work.

Longer answer: Most likely it worked with a previous release. MATSim includes defaults for often used leg modes. In older versions, when loading a config-file, the read-in values would just overwrite the corresponding default values. But this lead to problems in some rare cases, as all the default modes were still around, even in cases where this was not desired. So instead of just overwriting the specified modes' default values when loading a config-file, all the defaults now get removed, and only the values specified in the config-file will actually be used. This can be seen quite early in the log by the following statement:

```
INFO PlanCalcScoreConfigGroup:549 scoring parameters for subpopulation null were just replaced.
```

So, once `scoringParameters` parameter-set is loaded from the config-file, all defaults will be removed and replaced with the loaded parameters.

Due to this change, all modes must now be explicitly be defined in the config-file, while in earlier versions, only the parameters of modes differing from the defaults needed to be specified.
