### ISSUE TITLE
Discrete mode choice in combination with another contrib (RP)

### ISSUE THREAD

**Issue by gac55** [matsim-org/matsim-libs#1410]
We are testing the discrete mode choice contrib in combination with using road pricing. We are following @sebhoerl's great documentation from [here](https://github.com/matsim-org/matsim-libs/blob/master/contribs/discrete_mode_choice/docs/GettingStarted.md)

There appears to be some combination of these two contribs causing an issue with the initialisation of the config. We are using MATSim 12

The controller in question:

```
package com.arup.cm;

import org.apache.log4j.Logger;

import org.matsim.api.core.v01.Scenario;
import org.matsim.core.config.Config;
import org.matsim.core.config.ConfigUtils;
import org.matsim.core.controler.Controler;
import org.matsim.core.scenario.ScenarioUtils;

import ch.sbb.matsim.mobsim.qsim.SBBTransitModule;
import ch.sbb.matsim.config.SBBTransitConfigGroup;
import ch.sbb.matsim.mobsim.qsim.pt.SBBTransitEngineQSimModule;
import ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorModule;
import org.matsim.contrib.roadpricing.RoadPricingModule;
import org.matsim.contrib.roadpricing.RoadPricingUtils;
import org.matsim.contrib.roadpricing.RoadPricingConfigGroup;

import org.matsim.contribs.discrete_mode_choice.modules.DiscreteModeChoiceConfigurator;
import org.matsim.contribs.discrete_mode_choice.modules.DiscreteModeChoiceModule;

public class testDMCwithRP {

    public static void main(String[] args) {

        String configFilename = args[0];

        Config config = ConfigUtils.loadConfig(configFilename, RoadPricingUtils.createConfigGroup());
            
        ConfigUtils.addOrGetModule(config, RoadPricingConfigGroup.class).setTollLinksFile(args[1]);
        
        ConfigUtils.addOrGetModule(config, SBBTransitConfigGroup.class);

        DiscreteModeChoiceConfigurator.configureAsSubtourModeChoiceReplacement(config);        

        Scenario scenario = ScenarioUtils.loadScenario(config);
        Controler controler = new Controler(scenario);

        controler.addOverridingModule(new RoadPricingModule());
        controler.addOverridingModule(new SwissRailRaptorModule());
        controler.addOverridingModule(new DiscreteModeChoiceModule());
        
        controler.run();
    }
}
```

Returns:

```
2021-03-09T14:49:26,432  INFO Config:587 setting context to [file:/gc-test/dcmode.xml]
Exception in thread "main" java.lang.ClassCastException: class org.matsim.core.config.ConfigGroup cannot be cast to class org.matsim.contribs.discrete_mode_choice.modules.config.DiscreteModeChoiceConfigGroup (org.matsim.core.config.ConfigGroup and org.matsim.contribs.discrete_mode_choice.modules.config.DiscreteModeChoiceConfigGroup are in unnamed module of loader 'app')
	at org.matsim.contribs.discrete_mode_choice.modules.DiscreteModeChoiceConfigurator.configureAsSubtourModeChoiceReplacement(DiscreteModeChoiceConfigurator.java:39)
	at com.arup.cm.testDMCwithRP.main(testDMCwithRP.java:36)
```

I can't see an obvious cause in the [DiscreteModeChoiceConfigurator](https://github.com/matsim-org/matsim-libs/blob/12.x/contribs/discrete_mode_choice/src/main/java/org/matsim/contribs/discrete_mode_choice/modules/DiscreteModeChoiceConfigurator.java#L39)

**Comment by sebhoerl** [comment]
Indeed, very strange. I'll have a look.

**Comment by gac55** [comment]
Thanks @sebhoerl.

Am I right in saying that:

`DiscreteModeChoiceConfigurator.configureAsSubtourModeChoiceReplacement(config);`

Is equivalent to:

```
Config config = ConfigUtils.loadConfig(configFilename, new DiscreteModeChoiceConfigGroup());
```

Not sure I follow the difference, I think the readme says these are the same. If I load the `DiscreteModeChoiceConfigGroup` with the config I don't see this error

**Comment by sebhoerl** [comment]
No not really, the latter is just adding the config group, but it will not do anything. The `configureAsSubtourModeChoiceReplacement` will configure all the necessary things (configuring the choice model such that it is a replacement for SubtourModeChoice, adding DMC as a replanning strategy, ...). What is meant (I guess) is that after configuring DMC this way it works in the same way as SubtourModeChoice.

**Comment by gac55** [comment]
This was my mistake in the controller. For any future user, the following is correct:

```
    public static void main(String[] args) {

        String configFilename = args[0];

        Config config = ConfigUtils.loadConfig(configFilename, new DiscreteModeChoiceConfigGroup());

        DiscreteModeChoiceConfigurator.configureAsSubtourModeChoiceReplacement(config);

	    ConfigUtils.addOrGetModule(config, RoadPricingConfigGroup.class).setTollLinksFile(args[1]);
        ConfigUtils.addOrGetModule(config, SBBTransitConfigGroup.class);

        Scenario scenario = ScenarioUtils.loadScenario(config);
        Controler controler = new Controler(scenario);

        controler.addOverridingModule(new RoadPricingModule());
        controler.addOverridingModule(new SwissRailRaptorModule());
        controler.addOverridingModule(new DiscreteModeChoiceModule());
        
        controler.run();
```

In the logs we see evidence of both RP and DMC in use:

```
2021-03-19T11:50:05,575  INFO RoadPricingControlerListener:80 The sum of all paid tolls : 8073.699999999954 monetary units.
2021-03-19T11:50:05,580  INFO RoadPricingControlerListener:81 The number of people who paid toll : 2027
2021-03-19T11:50:05,580  INFO RoadPricingControlerListener:82 The average paid trip length : 5135.800082903636 m.
....
2021-03-19T11:50:11,400  INFO Counter:69 [DiscreteModeChoiceAlgorithm] handled plan # 8
2021-03-19T11:50:11,400  INFO Counter:69 [DiscreteModeChoiceAlgorithm] handled plan # 16
2021-03-19T11:50:11,400  INFO Counter:69 [DiscreteModeChoiceAlgorithm] handled plan # 32
2021-03-19T11:50:11,401  INFO Counter:69 [DiscreteModeChoiceAlgorithm] handled plan # 64
```
