### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin

### ISSUE THREAD

**Issue by cs071372** [matsim-org/matsim-libs#1431]
Hi all,

I am struggling 4 days now to deal with the error shown in the photo attached. 
I go in the matsim-libs/matsim folder and from there I do mvn clean install but after about 30-40min I get the error below. 
I checked on various forums, and I also tried the mvn clean install -U (to make any updates in case there is sth not updated), but with no luck either.
Also, mvn clean install -o (make an offline build) didnt work either.
The version of the surefire-plugin is 2.22.2.

I would really really appreciate any kind of help here. I am really stuck here :/

Thanks in advance

![165960980_1002686613803091_8306443700236828395_n](https://user-images.githubusercontent.com/81527875/112761422-ecf96100-9003-11eb-8af3-9d334853cce5.png)

**Comment by mrieser** [comment]
It would be interesting to know which test fails.

Anyway, you can suppress running the tests by adding `-DskipTests`, e.g. like this:

```
mvn clean install -DskipTests
```

**Comment by cs071372** [comment]
Error Log
-----------------------------------
sou[ERROR]
r[ERROR] Please refer to C:\Users\danie\IdeaProjects\EV_example_1\EV_example\matsim-libs\matsim\target\surefire-reports for the individual test results.
c[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
e[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
=[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk-11.0.10\bin\java" -Xmx700m -Djava.awt.headless=true -Dmatsim.preferLocalDtds=true -jar C:\Users\danie\AppData\Local\Temp\surefire7760263504403302503\surefirebooter17722045243836605157.jar C:\Users\danie\AppData\Local\Temp\surefire7760263504403302503 2021-03-28T21-21-36_622-jvmRun1 surefire6432644068096514839tmp surefire_014990650044723970602tmp"
o[ERROR] Process Exit Code: 0
r[ERROR] Crashed tests:
g[ERROR] org.matsim.withinday.replanning.identifiers.tools.ActivityReplanningMapTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
.mat[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk-11.0.10\bin\java" -Xmx700m -Djava.awt.headless=true -Dmatsim.preferLocalDtds=true -jar C:\Users\danie\AppData\Local\Temp\surefire7760263504403302503\surefirebooter17722045243836605157.jar C:\Users\danie\AppData\Local\Temp\surefire7760263504403302503 2021-03-28T21-21-36_622-jvmRun1 surefire6432644068096514839tmp surefire_014990650044723970602tmp"
s[ERROR] Process Exit Code: 0
i[ERROR] Crashed tests:
m.[ERROR] org.matsim.withinday.replanning.identifiers.tools.ActivityReplanningMapTest
a[ERROR]        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
p[ERROR]        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
i[ERROR]        at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
.c[ERROR]       at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
o[ERROR]        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
r[ERROR]        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
e[ERROR]        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
.v0[ERROR]      at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
1[ERROR]        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
.[ERROR]        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
popu[ERROR]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
l[ERROR]        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
at[ERROR]       at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
i[ERROR]        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
o[ERROR]        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
n[ERROR]        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
.[ERROR]        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
P[ERROR]        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
o[ERROR]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
p[ERROR]        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
u[ERROR]        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
l[ERROR]        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
a[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
t[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
i[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
o[ERROR]        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
---------------------------------------------------------------

I know I can skip the tests with that command, but isn't necessary to run the tests in order to build the pom? I cannot really feel the value these tests.
Also, I want to ask sth more: I am currently working on an ev project. 
In the ev folder there is a pom file as well. 
I want to ask if there is a specific order in which I should do the build of the pom files. 
What I mean is, should I first build the pom in the ev folder, then go back in the matsim-libs/matsim/ and build that pom and finally build the pom at matsim-libs? Does this order make any difference?

Thanks in advance

**Comment by mrieser** [comment]
Typically, all the tests are regularly run during development, so normally they should just work. Based on your error log, the test crashed the JVM, which is very uncommon.

You can install the pom and jar files also when skipping the tests.

The ev project will require MATSim as a dependency. So you should first `mvn install` MATSim, and after that the ev project.

Do you plan to write a lot of code, maybe even changing parts of MATSim? For most users that just "use" MATSim and maybe "extend" it a little bit, it's usually best not to install MATSim itself, but only use it as a dependency by using the [matsim-example-project](https://github.com/matsim-org/matsim-example-project), which will load MATSim as a Maven dependency.

**Comment by cs071372** [comment]
I build the pom file of matsim-libs/matsim by skipping the tests and it gives a SUCCESS this time. Also, while I build the pom of the ev folder WITH tests, it also gave a SUCCESS build. In my case, seems to be a little confusing when the tests run with no error and when not. Anyway, now it seems that I am on a correct path, I hope the fact that I skipped the test of matsim-libs/matsim do not appear as a problem later on.

Thanks a lot for the help.
