### ISSUE TITLE
DMC DefaultModeChainGenerator - java.lang.IndexOutOfBoundsException: Index -2 out of bounds for length 11

### ISSUE THREAD

**Issue by gac55** [matsim-org/matsim-libs#1437]
Strange one, logging here:

```
2021-04-07T12:29:02,270 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread DiscreteModeChoiceAlgorithm.14 died with exception. Will stop after all threads finished.
java.lang.IndexOutOfBoundsException: Index -2 out of bounds for length 11
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
        at org.matsim.contribs.discrete_mode_choice.model.mode_chain.DefaultModeChainGenerator.next(DefaultModeChainGenerator.java:75) ~[discrete_mode_choice-12.0.jar:?]
        at org.matsim.contribs.discrete_mode_choice.model.mode_chain.DefaultModeChainGenerator.next(DefaultModeChainGenerator.java:26) ~[discrete_mode_choice-12.0.jar:?]
        at org.matsim.contribs.discrete_mode_choice.model.tour_based.TourBasedModel.chooseModes(TourBasedModel.java:85) ~[discrete_mode_choice-12.0.jar:?]
        at org.matsim.contribs.discrete_mode_choice.replanning.DiscreteModeChoiceAlgorithm.run(DiscreteModeChoiceAlgorithm.java:53) ~[discrete_mode_choice-12.0.jar:?]
        at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234) ~[matsim-12.0.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2021-04-07T12:29:02,278  INFO AbstractMultithreadedModule:156 [DiscreteModeChoiceAlgorithm] all 32 threads finished.
2021-04-07T12:29:02,278 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Some threads crashed, thus not all plans may have been handled.
        at org.matsim.core.replanning.modules.AbstractMultithreadedModule.finishReplanning(AbstractMultithreadedModule.java:159) ~[matsim-12.0.jar:?]
        at org.matsim.core.replanning.GenericPlanStrategyImpl.finish(GenericPlanStrategyImpl.java:114) ~[matsim-12.0.jar:?]
        at org.matsim.core.replanning.GenericStrategyManager.run(GenericStrategyManager.java:223) ~[matsim-12.0.jar:?]
        at org.matsim.core.replanning.StrategyManager.run(StrategyManager.java:191) ~[matsim-12.0.jar:?]
        at org.matsim.core.replanning.StrategyManager.run(StrategyManager.java:173) ~[matsim-12.0.jar:?]
        at org.matsim.core.controler.corelisteners.PlansReplanningImpl.notifyReplanning(PlansReplanningImpl.java:58) ~[matsim-12.0.jar:?]
        at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerReplanningEvent(ControlerListenerManagerImpl.java:206) ~[matsim-12.0.jar:?]
        at org.matsim.core.controler.AbstractController$3.run(AbstractController.java:140) ~[matsim-12.0.jar:?]
        at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:230) ~[matsim-12.0.jar:?]
        at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:137) ~[matsim-12.0.jar:?]
        at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:113) ~[matsim-12.0.jar:?]
        at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80) ~[matsim-12.0.jar:?]
        at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-12.0.jar:?]
        at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-12.0.jar:?]
        at org.matsim.core.controler.AbstractController.run(AbstractController.java:88) [matsim-12.0.jar:?]
        at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-12.0.jar:?]
        at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-12.0.jar:?]
        at com.arup.cm.RunMatsimDMC.main(RunMatsimDMC.java:41) [classes/:?]
Caused by: java.lang.IndexOutOfBoundsException: Index -2 out of bounds for length 11
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
        at org.matsim.contribs.discrete_mode_choice.model.mode_chain.DefaultModeChainGenerator.next(DefaultModeChainGenerator.java:75) ~[discrete_mode_choice-12.0.jar:?]
        at org.matsim.contribs.discrete_mode_choice.model.mode_chain.DefaultModeChainGenerator.next(DefaultModeChainGenerator.java:26) ~[discrete_mode_choice-12.0.jar:?]
        at org.matsim.contribs.discrete_mode_choice.model.tour_based.TourBasedModel.chooseModes(TourBasedModel.java:85) ~[discrete_mode_choice-12.0.jar:?]
        at org.matsim.contribs.discrete_mode_choice.replanning.DiscreteModeChoiceAlgorithm.run(DiscreteModeChoiceAlgorithm.java:53) ~[discrete_mode_choice-12.0.jar:?]
        at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234) ~[matsim-12.0.jar:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
2021-04-07T12:29:02,279  INFO MatsimRuntimeModifications:79 S H U T D O W N   ---   start shutdown.
2021-04-07T12:29:02,279 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
```

DMC config. I don't think anything here could cause this:

```
  <module name="DiscreteModeChoice">
    <param name="modelType" value="Tour" />
    <param name="selector" value="MultinomialLogit" />
    <param name="tourConstraints" value="VehicleContinuity" />
    <param name="tourFinder" value="ActivityBased" />
    <param name="tourEstimator" value="MATSimDayScoring" />

    <!-- So it uses the car mode map. -->
    <param name="modeAvailability" value="Car" />

    <param name="cachedModes" value="car,bus_dublin,bus_interurban_rural,bus_other_city_town,heavy_rail_other,heavy_rail_dart,light_rail_luas_red,light_rail_luas_green,ferry,walk,bike" />

    <parameterset type="modeAvailability:Car" >
      <param name="availableModes" value="car,bus_dublin,bus_interurban_rural,bus_other_city_town,heavy_rail_other,heavy_rail_dart,light_rail_luas_red,light_rail_luas_green,ferry,walk,bike" />
    </parameterset>

    <parameterset type="tripEstimator:MATSimTripScoring" >
      <!-- Modes which are considered as public transit, i.e. they involve waiting for a vehicle. -->
      <param name="ptLegModes" value="bus_dublin,bus_interurban_rural,bus_other_city_town,heavy_rail_other,heavy_rail_dart,light_rail_luas_red,light_rail_luas_green,ferry" />
    </parameterset>

  </module>
```

**Comment by gac55** [comment]
FYI @sebhoerl. I should be able to get to the bottom of the cause

**Comment by synas34** [comment]
This error is occuring because of your simulation is very large and is causing an Integer Overflow in DefaultModeChainGenerator for the index variable.

```
		int copy = index;

		for (int k = 0; k < numberOfTrips; k++) {
			chain.add(availableModes.get(copy % numberOfModes));
			copy -= copy % numberOfModes;
			copy /= numberOfModes;
		}
```

In Java, an int is a 32-bit signed integer, which can represent values from -2,147,483,648 to 2,147,483,647. When the index variable gets incremented above 2,147,483,647, the number will "wrap around" and start from the other end of the range. This is what is leading to the Out of Bounds error.

```
2021-04-07T12:29:02,270 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread DiscreteModeChoiceAlgorithm.14 died with exception. Will stop after all threads finished.
java.lang.IndexOutOfBoundsException: Index -2 out of bounds for length 11
```

One solution is to change the datatype to a long or BigInteger type to handle the large index. I solved the issue like so:

```

public class DefaultModeChainGenerator implements ModeChainGenerator {
	final private List<String> availableModes;

	final private int numberOfTrips;
	final private int numberOfModes;

	final private long maximumAlternatives;

	private long index = 0;                                                           // Changed to long

	public DefaultModeChainGenerator(Collection<String> availableModes, int numberOfTrips) {
		this.availableModes = new ArrayList<>(availableModes);
		this.numberOfModes = availableModes.size();
		this.numberOfTrips = numberOfTrips;
		this.maximumAlternatives = ArithmeticUtils.pow((long) numberOfModes, numberOfTrips);
	}

	public long getNumberOfAlternatives() {
		return maximumAlternatives;
	}

	@Override
	public boolean hasNext() {
		return index < maximumAlternatives;
	}

	@Override
	public List<String> next() {
		if (!hasNext()) {
			throw new IllegalStateException();
		}

		List<String> chain = new ArrayList<>(numberOfTrips);
		long copy = index;                                                                                          // Changed to long

		for (int k = 0; k < numberOfTrips; k++) {
			chain.add(availableModes.get((int) (copy % numberOfModes)));          // Cast required here
			copy -= copy % numberOfModes;
			copy /= numberOfModes;
		}

		index++;

		return chain;
	}

	static public class Factory implements ModeChainGeneratorFactory {
		@Override
		public ModeChainGenerator createModeChainGenerator(Collection<String> modes, Person person,
				List<DiscreteModeChoiceTrip> trips) {
			return new DefaultModeChainGenerator(modes, trips.size());
		}
	}
}

```
I changed the copy and index variables to long and casted it to an int for the modulus line so the rest of the code works fine.

**Comment by sebhoerl** [comment]
@gac55 Sorry, I didn't see the issue bacck then.
@synas34 Yes, chaging to `long` may be an option, but it will still evaluate a huge amount of alternatives. It usually makes more sense to restrict the number of alternatives using a `TourLengthFilter` or something similar (excluding the person with the long activity chain from mode choice, you seem to have one with 10 activities). 

Probably with long we are safe, but I think there was also an issue of memory consumption. I think @tkchouaki had a solution that we might be able to add here?

**Comment by KasiaKoz** [comment]
Yeah I don't think we would want to allow this many alternatives, especially as they seem to be generated for every person for every iteration (even though they are the same given the same number of modes and trips?). We've used the `TourLengthFilter` with number of trips bounded by `log_(number of modes in dmc config) (2147483647)` and that got rid of the error.

Not a solution but thought I'd mention anyway, on our end I just added a check in the `DefaultModeChainGenerator` constructor to fail faster
```java
		if (this.maximumAlternatives > 2147483647) {
			throw new RuntimeException(String.format(
				"Number of Available Modes: %d and Trips: %d results in too many combinations to consider: %d",
				this.numberOfModes,
				this.numberOfTrips,
				this.maximumAlternatives
			));
		}
```

**Comment by tkchouaki** [comment]
@sebhoerl, @synas34 yes changing the index type works fine. Plus if you have more alternatives that what long can count you will get a MathArithmeticException from the call to ArithmeticUtils.pow in the constructor, so that's a fast fail. 

If you really need to go beyond that, I wrote this chain generator that keeps the current mode index of each trip. It takes a bit more memory and slightly more time. A check is done at the construction time to see if the functionality is needed. If not it uses the default one as a delegate. So you can just bind the chain generator to this one instead of the default. 

@sebhoerl if you think this should be added to the repo I could make a pull request. 

package org.matsim.contribs.discrete_mode_choice.model.mode_chain;


```java
package org.matsim.contribs.discrete_mode_choice.model.mode_chain;

import org.apache.commons.math3.exception.MathArithmeticException;
import org.apache.commons.math3.util.ArithmeticUtils;
import org.matsim.api.core.v01.population.Person;
import org.matsim.contribs.discrete_mode_choice.model.DiscreteModeChoiceTrip;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

public class LongToursAdaptedModeChainGenerator implements ModeChainGenerator {

    private final int numberOfTrips;
    private int[] modeIndexPerTrip;
    private final List<String> availableModes;
    private long numberOfAlternatives;
    private boolean haveNext;
    private ModeChainGenerator delegate;

    public LongToursAdaptedModeChainGenerator(Collection<String> availableModes, int numberOfTrips) {
        this.numberOfTrips = numberOfTrips;
        this.availableModes = new ArrayList<>(availableModes);

        try {
            this.numberOfAlternatives = ArithmeticUtils.pow((long) availableModes.size(), numberOfTrips);
            this.haveNext = numberOfTrips > 0 && availableModes.size() > 0;
            this.delegate = new DefaultModeChainGenerator(availableModes, numberOfTrips);
        } catch (MathArithmeticException e) {
            this.numberOfAlternatives = -1;
            this.modeIndexPerTrip = new int[numberOfTrips];
            for(int i=0; i<numberOfTrips; i++) {
                this.modeIndexPerTrip[i] = 0;
            }
        }
    }

    @Override
    public long getNumberOfAlternatives() {
        return this.numberOfAlternatives;
    }

    @Override
    public boolean hasNext() {
        if(this.delegate == null) {
            return this.haveNext;
        } else {
            return delegate.hasNext();
        }
    }

    @Override
    public List<String> next() {
        if(delegate != null) {
            return delegate.next();
        }
        List<String> chain = new ArrayList<>();
        int carry = 1;
        for(int i=0; i<numberOfTrips; i++) {
            chain.add(this.availableModes.get(this.modeIndexPerTrip[i]));
            this.modeIndexPerTrip[i] += carry;
            if (this.modeIndexPerTrip[i] == this.availableModes.size()) {
                this.modeIndexPerTrip[i] = 0;
            } else {
                carry = 0;
            }
        }
        this.haveNext = carry == 0;
        return chain;
    }



    static public class Factory implements ModeChainGeneratorFactory {
        @Override
        public ModeChainGenerator createModeChainGenerator(Collection<String> modes, Person person,
                                                           List<DiscreteModeChoiceTrip> trips) {
            return new LongToursAdaptedModeChainGenerator(modes, trips.size());
        }
    }
}

```

**Comment by sebhoerl** [comment]
Let's add it @tkchouaki

**Comment by gac55** [comment]
Maybe when we have more than 2,147,483,647 choices, perhaps we need to restrict the choices instead of handling that ridiculously large number?

**Comment by gac55** [comment]
Some further notes on this, for the benefit of those who may follow behind us ;) This is a summary of this conversation and what we did in the end to get things working.

The total number of alternatives entering the logit calculation depends on the number of tour activities and the number of modes​. 

We often make use of the SBB mode mapping functionality, which permits us to break up `pt` into a list of modes which can be given different parameters. For example, we can have premium long distance rail, shorter commuter rail etc all with different costs. As a consequence, out modes list may explode.

In combination with this it is also possible we may have agents with long tours. When we have long tours, and lots of modes, combinatorial explosion can occur:

_With 10 modes:​_

3 activities: 10^3 alts​

4 activities: 10^4 alts​

8 activities: 10^8 alts​


_With 7 modes:​​_

3 activities: 343 alts​​

4 activities: 2,401 alts​​

8 activities: 5,764,801 alts

So, we must think about sensibly managing the choice sets to get the most out of DMC and not unnecessarily explore an almost impossible problem space. 

In the end, we may more sensibly define modes ensuring a mode is defined only when absolutely necessary (i.e. needs different parameters) and by doing an analysis of the prevalence of long tours in your population to decide on a reasonable  value to use `TourLengthFilter`. It is likely that ~95% of your population will only be doing tours of length 4 or 5.

If you do this, you'll see the benefits of the wonderful DMC ;) 

@sebhoerl feel free to keep this open if you do want to make changes to handle a large choice set, but I think on balance best to advise users to manage the combinations and not brute force it so I've close it with this comment ;)
