### ISSUE TITLE
otfvis: cannot press "step" while simulation is playing

### ISSUE THREAD

**Issue by kainagel** [matsim-org/matsim-libs#1447]
In this state:
![image](https://user-images.githubusercontent.com/8777649/114306768-35714e00-9add-11eb-8edf-727db7d4990c.png)
(i.e. simulation is running; one could press the pause button) pressing the step button (single triangle) aborts the simulation:
```
...2021-04-11T15:45:41,421  INFO QSim:542 SIMULATION (NEW QSim) AT 04:00:00 : #Veh=288124 lost=0 simT=14400.0s realT=74s; (s/r): 194.59459459459458
2021-04-11T15:45:49,147  INFO AbstractQNetsimEngine:365 SIMULATION (QNetsimEngine) AT 05:00:00 : #links=4244 #nodes=557
2021-04-11T15:45:49,148  INFO QSim:542 SIMULATION (NEW QSim) AT 05:00:00 : #Veh=285190 lost=0 simT=18000.0s realT=82s; (s/r): 219.5121951219512
2021-04-11T15:46:20,287  INFO MemoryObserver:41 used RAM: 3350 MB  free: 649 MB  total: 4000 MB
2021-04-11T15:46:30,548 ERROR MatsimRuntimeModifications$1:62 Getting uncaught Exception in Thread AWT-EventQueue-0
java.lang.IllegalStateException: null
	at org.matsim.core.mobsim.framework.PlayPauseSimulationControl.doStep(PlayPauseSimulationControl.java:87) ~[matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.vis.otfvis.OnTheFlyServer.doStep(OnTheFlyServer.java:311) ~[otfvis-13.0-20210407.204757-353.jar:?]
	at org.matsim.vis.otfvis.OnTheFlyServer.requestNewTime(OnTheFlyServer.java:321) ~[otfvis-13.0-20210407.204757-353.jar:?]
	at org.matsim.vis.otfvis.gui.OTFHostControl.requestTimeStep(OTFHostControl.java:88) ~[otfvis-13.0-20210407.204757-353.jar:?]
	at org.matsim.vis.otfvis.gui.OTFControlBar$5.actionPerformed(OTFControlBar.java:148) ~[otfvis-13.0-20210407.204757-353.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6636) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6401) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2263) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5012) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4844) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2764) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4844) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
2021-04-11T15:46:31,244 ERROR AbstractController:222 Mobsim did not complete normally! afterMobsimListeners will be called anyway.
java.lang.RuntimeException: java.lang.InterruptedException
	at org.matsim.core.mobsim.qsim.qnetsimengine.QNetsimEngineWithThreadpool.run(QNetsimEngineWithThreadpool.java:110) ~[matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.mobsim.qsim.qnetsimengine.AbstractQNetsimEngine.doSimStep(AbstractQNetsimEngine.java:225) ~[matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:395) ~[matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:254) ~[matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) ~[matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:211) ~[matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243) ~[matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207) [matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154) [matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121) [matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81) [matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-13.0-20210407.195228-252.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-13.0-20210407.195228-252.jar:?]
	at playground.kairuns.run.KNTransitControler.main(KNTransitControler.java:160) [classes/:?]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:418) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:190) ~[?:?]
	at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:247) ~[?:?]
	at org.matsim.core.mobsim.qsim.qnetsimengine.QNetsimEngineWithThreadpool.run(QNetsimEngineWithThreadpool.java:106) ~[matsim-13.0-20210407.195228-252.jar:?]
	... 16 more
2021-04-11T15:46:31,249  WARN CharyparNagelActivityScoring:246 The first and the last activity do not have the same type. 
2021-04-11T15:46:31,249  WARN CharyparNagelActivityScoring:247 Will score the first activity from midnight to its end, and the last activity from its start to midnight.
2021-04-11T15:46:31,249  WARN CharyparNagelActivityScoring:248 Because of the nonlinear function, this is not the same as scoring from start to end.
...
```

**Comment by michalmac** [comment]
I played a bit. Looks like this may happen when clicking single/multi-step forward buttons while in the async mode.
