### ISSUE TITLE
 INFO MemoryObserver:41 used RAM: 2543 MB

### ISSUE THREAD

**Issue by cs071372** [matsim-org/matsim-libs#1489]
Hi, I m facing a problem while doing a big number of simulations on Matsim. The simulation is called 10 times and each time it makes 40 simulation runs, thus, 40*10 simulation runs. However, At some point, after 6-7hours of running I receive the log below at my outputlog and from that point nothing else happends. It seems like it never terminates.
I cannot see what this MemoryObserver is? Might be a java problem? Or some memory problem at some point?
Thanks in advance
````
2021-05-06T15:43:28,317 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.21 died with exception. Will stop after all threads finished.

java.lang.NullPointerException: null
                at org.matsim.core.router.AStarEuclidean.addToPendingNodes(AStarEuclidean.java:176) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.Dijkstra.relaxNodeLogic(Dijkstra.java:423) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.AbstractFastRouterDelegate.relaxNode(AbstractFastRouterDelegate.java:99) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.FastAStarLandmarks.relaxNode(FastAStarLandmarks.java:128) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.Dijkstra.searchLogic(Dijkstra.java:318) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.Dijkstra.calcLeastCostPath(Dijkstra.java:237) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.AStarLandmarks.calcLeastCostPath(AStarLandmarks.java:125) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.FastAStarLandmarks.calcLeastCostPath(FastAStarLandmarks.java:79) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.NetworkRoutingModule.calcRoute(NetworkRoutingModule.java:95) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.contrib.ev.routing.MyEvNetworkRoutingModule.calcRoute(MyEvNetworkRoutingModule.java:125) ~[classes/:?]
                at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:174) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.PlanRouter.run(PlanRouter.java:94) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234) ~[matsim-12.0-SNAPSHOT.jar:?]
                at java.lang.Thread.run(Thread.java:834) [?:?]
2021-05-06T15:43:28,332 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.20 died with exception. Will stop after all threads finished.
java.lang.NullPointerException: null
                at org.matsim.core.router.AStarEuclidean.addToPendingNodes(AStarEuclidean.java:176) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.Dijkstra.relaxNodeLogic(Dijkstra.java:423) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.AbstractFastRouterDelegate.relaxNode(AbstractFastRouterDelegate.java:99) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.FastAStarLandmarks.relaxNode(FastAStarLandmarks.java:128) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.Dijkstra.searchLogic(Dijkstra.java:318) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.Dijkstra.calcLeastCostPath(Dijkstra.java:237) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.AStarLandmarks.calcLeastCostPath(AStarLandmarks.java:125) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.FastAStarLandmarks.calcLeastCostPath(FastAStarLandmarks.java:79) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.NetworkRoutingModule.calcRoute(NetworkRoutingModule.java:95) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.contrib.ev.routing.MyEvNetworkRoutingModule.calcRoute(MyEvNetworkRoutingModule.java:125) ~[classes/:?]
                at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:174) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.PlanRouter.run(PlanRouter.java:94) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234) ~[matsim-12.0-SNAPSHOT.jar:?]
                at java.lang.Thread.run(Thread.java:834) [?:?]

2021-05-06T15:43:28,317 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.16 died with exception. Will stop after all threads finished.

java.lang.NullPointerException: null
                at org.matsim.core.router.AStarEuclidean.addToPendingNodes(AStarEuclidean.java:176) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.Dijkstra.relaxNodeLogic(Dijkstra.java:423) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.AbstractFastRouterDelegate.relaxNode(AbstractFastRouterDelegate.java:99) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.FastAStarLandmarks.relaxNode(FastAStarLandmarks.java:128) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.Dijkstra.searchLogic(Dijkstra.java:318) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.Dijkstra.calcLeastCostPath(Dijkstra.java:237) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.AStarLandmarks.calcLeastCostPath(AStarLandmarks.java:125) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.FastAStarLandmarks.calcLeastCostPath(FastAStarLandmarks.java:79) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.NetworkRoutingModule.calcRoute(NetworkRoutingModule.java:95) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.contrib.ev.routing.MyEvNetworkRoutingModule.calcRoute(MyEvNetworkRoutingModule.java:125) ~[classes/:?]
                at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:174) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.router.PlanRouter.run(PlanRouter.java:94) ~[matsim-12.0-SNAPSHOT.jar:?]
                at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234) ~[matsim-12.0-SNAPSHOT.jar:?]
                at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by mrieser** [comment]
The MemoryObserver is independent, it just regularly reports the current memory usage.

In your case, you have an exception during the shortest path search ("routing"). This is very uncommon, as this part is very often used and pretty well tested.

I see that you use a rather old version (`matsim-12.0-SNAPSHOT.jar`). MATSim 12.0 was released in 2020, MATSim 13.0 in 2021, so your version is at least 1.5 years old. There was [an issue](https://github.com/matsim-org/matsim-code-examples/issues/314) last year where a problem in routing came up randomly in some configurations (e.g. only when running on Java 11, not when running on Java 8). So I suggest to try to use a newer version of MATSim and see if the problem still occurs.
