### ISSUE TITLE
Possible concurrency issue in Hermes

### ISSUE THREAD

**Issue by mfitz** [matsim-org/matsim-libs#1876]
Hi

We've been running some simulations using MATSim 14 snapshot and Hermes. With a subset of these simulations, the simulation almost always (but **not** always) grinds to a halt. When we replace Hermes with QSim and run the same simulations, they run to completion with no issue. 

The log files in the failure cases always look like this, with seemingly only the memory observer thread doing anything after the end of a Hermes cycle:

```
...
2022-02-08T01:12:39,111  INFO Realm:325 Hermes running at 24:00:00
2022-02-08T01:12:39,138  INFO Realm:325 Hermes running at 25:00:00
2022-02-08T01:12:39,149  INFO Realm:325 Hermes running at 26:00:00
2022-02-08T01:12:39,151  INFO SingleHandlerEventsManager:180  event # 16777216
2022-02-08T01:12:39,158  INFO Realm:325 Hermes running at 27:00:00
2022-02-08T01:12:39,165  INFO Realm:325 Hermes running at 28:00:00
2022-02-08T01:12:39,169  INFO Realm:325 Hermes running at 29:00:00
2022-02-08T01:12:39,172  INFO Realm:325 Hermes running at 30:00:00
2022-02-08T01:12:39,174  INFO Realm:325 Hermes running at 31:00:00
2022-02-08T01:12:39,176  INFO Hermes:76 Hermes took 10331 ms
2022-02-08T01:13:34,420  INFO MemoryObserver:41 used RAM: 13999 MB  free: 4920 MB  total: 18920 MB
2022-02-08T01:14:34,421  INFO MemoryObserver:41 used RAM: 14138 MB  free: 4781 MB  total: 18920 MB
2022-02-08T01:15:34,421  INFO MemoryObserver:41 used RAM: 14274 MB  free: 4645 MB  total: 18920 MB
2022-02-08T01:16:34,422  INFO MemoryObserver:41 used RAM: 14411 MB  free: 4508 MB  total: 18920 MB
2022-02-08T01:17:34,422  INFO MemoryObserver:41 used RAM: 14546 MB  free: 4373 MB  total: 18920 MB
2022-02-08T01:18:34,422  INFO MemoryObserver:41 used RAM: 14684 MB  free: 4235 MB  total: 18920 MB
2022-02-08T01:19:34,423  INFO MemoryObserver:41 used RAM: 14819 MB  free: 4100 MB  total: 18920 MB
2022-02-08T01:20:34,423  INFO MemoryObserver:41 used RAM: 14956 MB  free: 3963 MB  total: 18920 MB
2022-02-08T01:21:34,424  INFO MemoryObserver:41 used RAM: 15093 MB  free: 3826 MB  total: 18920 MB
2022-02-08T01:22:34,425  INFO MemoryObserver:41 used RAM: 15222 MB  free: 3697 MB  total: 18920 MB
2022-02-08T01:23:34,426  INFO MemoryObserver:41 used RAM: 15360 MB  free: 3559 MB  total: 18920 MB
2022-02-08T01:24:34,427  INFO MemoryObserver:41 used RAM: 15496 MB  free: 3423 MB  total: 18920 MB
2022-02-08T01:25:34,429  INFO MemoryObserver:41 used RAM: 15632 MB  free: 3287 MB  total: 18920 MB
2022-02-08T01:26:34,430  INFO MemoryObserver:41 used RAM: 15769 MB  free: 3150 MB  total: 18920 MB
2022-02-08T01:27:34,431  INFO MemoryObserver:41 used RAM: 8321 MB  free: 10598 MB  total: 18920 MB
2022-02-08T01:28:34,433  INFO MemoryObserver:41 used RAM: 8459 MB  free: 10460 MB  total: 18920 MB
2022-02-08T01:29:34,434  INFO MemoryObserver:41 used RAM: 8597 MB  free: 10322 MB  total: 18920 MB
2022-02-08T01:30:34,435  INFO MemoryObserver:41 used RAM: 8731 MB  free: 10188 MB  total: 18920 MB
2022-02-08T01:31:34,436  INFO MemoryObserver:41 used RAM: 8867 MB  free: 10052 MB  total: 18920 MB
...
```

It continues like this for hours and hours, until we kill the process. The CPU cores are barely being touched at all and the memory usage on the box is well inside the limits:

<img width="1440" alt="Screen Shot 2022-02-08 at 01 45 54" src="https://user-images.githubusercontent.com/250899/153033460-589cebbe-24e3-4121-adbb-b9c46a811006.png">

In the most recent case, I let the process continue running and took a number of thread dumps via `jcmd`. They all contain descriptions of some of the same threads in the same states, for example:

```
...
"main" #1 prio=5 os_prio=0 cpu=216030.22ms elapsed=5693.62s tid=0x00007f2750016800 nid=0x7c1f in Object.wait()  [0x00007f27597bb000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.13/Native Method)
        - waiting on <no object reference available>
        at org.matsim.core.events.ParallelEventsManager$Distributor.flush(ParallelEventsManager.java:271)
        - waiting to re-lock in wait() <0x00000001b3c91358> (a org.matsim.core.events.ParallelEventsManager$Distributor)
        at org.matsim.core.events.ParallelEventsManager.flush(ParallelEventsManager.java:246)
        at org.matsim.core.events.ParallelEventsManager.finishProcessing(ParallelEventsManager.java:217)
        - locked <0x00000000cb76ba98> (a org.matsim.core.events.ParallelEventsManager)
        at org.matsim.core.mobsim.hermes.Hermes.run(Hermes.java:81)
        at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124)
        at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:211)
        at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243)
        at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207)
        at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154)
        at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121)
        at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81)
        at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
        at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
        at org.matsim.core.controler.AbstractController.run(AbstractController.java:89)
        at org.matsim.core.controler.NewControler.run(NewControler.java:82)
        at org.matsim.core.controler.Controler.run(Controler.java:249)
        at com.arup.cm.roadpricing.run.RunMatsimCappedRP.main(RunMatsimCappedRP.java:56)
...
"EventsDistributor" #3892 daemon prio=5 os_prio=0 cpu=22851.40ms elapsed=2231.26s tid=0x00007f2750dcb000 nid=0x2243 in Object.wait()  [0x00007f24edaf8000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.13/Native Method)
	- waiting on <no object reference available>
	at org.matsim.core.events.ParallelEventsManager$Distributor.run(ParallelEventsManager.java:306)
	- waiting to re-lock in wait() <0x00000001b3c91358> (a org.matsim.core.events.ParallelEventsManager$Distributor)
```
Although the thread dump itself does not directly identify a deadlock, this feels like a deadlock to me, or more likely one or more threads waiting for notifications from a monitor that never come. My other guess would be some kind of infinite loop, but there is no evidence of that.

The `main` thread is always stuck on Line 81 in the Hermes class, [asking the events manager to finish processing](https://github.com/matsim-org/matsim-libs/blob/3dc0b2f679802c9a11d1ce8ee87d68975f692451/matsim/src/main/java/org/matsim/core/mobsim/hermes/Hermes.java?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L81), which ultimately ends up further down the stack inside [a synchronized block inside ParallelEventsManager.Distributor](https://github.com/matsim-org/matsim-libs/blob/3dc0b2f679802c9a11d1ce8ee87d68975f692451/matsim/src/main/java/org/matsim/core/events/ParallelEventsManager.java#L271). The thread is apparently never being notified.

In that same `Distributor` class, I see the same lock being taken out inside the run method, where [the call to notify seems to be dependent on the event queue being empty](https://github.com/matsim-org/matsim-libs/blob/3dc0b2f679802c9a11d1ce8ee87d68975f692451/matsim/src/main/java/org/matsim/core/events/ParallelEventsManager.java#L316). I don't know or understand the code well enough to have any ideas about why `notify` is never called, but it does look like the two threads above are waiting for notification from the same monitor.

I can supply all of our input and config files if it will help, but first I was wondering if anybody has seen this same behaviour before.

Some basic environmental detail:

```bash
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

```bash
$JAVA_HOME/bin/java --version
openjdk 11.0.13 2021-10-19 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8-LTS, mixed mode, sharing)
```

```xml
        <dependency>
            <!-- This is the matsim "core": -->
            <groupId>org.matsim</groupId>
            <artifactId>matsim</artifactId>
            <version>14.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.matsim.contrib</groupId>
            <artifactId>roadpricing</artifactId>
            <version>14.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.matsim.contrib</groupId>
            <artifactId>multimodal</artifactId>
            <version>14.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.matsim.contrib</groupId>
            <artifactId>sbb-extensions</artifactId>
            <version>14.0-SNAPSHOT</version>
        </dependency>
```

**Comment by mrieser** [comment]
In your `config.xml`, look for `parallelEventHandling` and there for `eventsQueueSize`. Increase that value and try again.

I've observed similar behavior in simulations where event handlers create additional events (not sure if this is the case in your simulation). When a lot of those additional events are generated, it is possible for an internal data structure to become full, and then the code waits to be able to insert the new event. But as the new event is created while processing events, and this processing gets blocked, there will never be an event be taken out of the queue, und thus it hangs.

**Comment by captainnemo2005** [comment]
Hi @mrieser ,

My cases: I run MATSim 10 iteration and then run a metacalibration to calibrate some parameters for MATSim and again feed them back to MATSim. The first iteration is fine and when I update the parameter and rerun this issue happened during the PlanRouter. 
I ran to the similar issue but during the PlanRouter Phase:

[DEBUG] 06.03.2022 15:09:01.016 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=car
[DEBUG] 06.03.2022 15:09:01.016 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=car
[DEBUG] 06.03.2022 15:09:01.016 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=walk
[DEBUG] 06.03.2022 15:09:01.016 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=ride
[DEBUG] 06.03.2022 15:09:01.019 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=ride
[DEBUG] 06.03.2022 15:09:01.022 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=car
[DEBUG] 06.03.2022 15:09:01.022 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=car
[DEBUG] 06.03.2022 15:09:01.022 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=car
[DEBUG] 06.03.2022 15:09:01.022 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=car
[DEBUG] 06.03.2022 15:09:01.023 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=walk
[DEBUG] 06.03.2022 15:09:01.023 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=walk
[DEBUG] 06.03.2022 15:09:01.023 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=walk
[DEBUG] 06.03.2022 15:09:01.023 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=walk
[DEBUG] 06.03.2022 15:09:01.023 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=ride
[DEBUG] 06.03.2022 15:09:01.024 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=walk
[DEBUG] 06.03.2022 15:09:01.024 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=walk
[DEBUG] 06.03.2022 15:09:01.024 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=ride
[DEBUG] 06.03.2022 15:09:01.025 [PersonPrepareForSim.0] PlanRouter - about to call TripRouter with routingMode=car
[INFO ] 06.03.2022 15:09:55.257 [MemoryPrinter] MemoryObserver - used RAM: 2642 MB  free: 9409 MB  total: 12052 MB
[INFO ] 06.03.2022 15:10:55.263 [MemoryPrinter] MemoryObserver - used RAM: 4106 MB  free: 7945 MB  total: 12052 MB
[INFO ] 06.03.2022 15:11:55.275 [MemoryPrinter] MemoryObserver - used RAM: 3234 MB  free: 8817 MB  total: 12052 MB
[INFO ] 06.03.2022 15:12:55.287 [MemoryPrinter] MemoryObserver - used RAM: 6376 MB  free: 4731 MB  total: 11108 MB

I used the SwissRaptor router.  I used MATSim 13 and JAVA 14 JDK. 
Population is around 50k agents.

I tried to increased the eventsQueueSize to around 500k (was around 100k) but the problem still the same.

Do you know what eventually causes this issue?

**Comment by erasky** [comment]
Have you solved the problem? @mfitz

**Comment by mfitz** [comment]
Hi @erasky 

Yes, we solved the problem thanks to the answer from @mrieser. To add a little more detail:

I wasn't sure what value to use for `eventsQueueSize`, so I started by quadrupling the old default value as found [here](https://github.com/matsim-org/matsim-libs/blob/4a91e950073bab816e3e1ba16776b4a0e93d1881/matsim/src/main/java/org/matsim/core/events/ParallelEventsManager.java#L56). The simulation failed in the same way, so I doubled the value, and then again, but still we had the same issue. In the end I parsed the MATSim log file of the hanging simulation to find the highest event number logged, reasoning that setting the events queue to a size big enough to accommodate all events ever in an iteration would surely make it big enough (but possibly too big). So we based the value on the biggest number in log lines like:

```bash
2022-02-08T01:12:39,151  INFO SingleHandlerEventsManager:180  event # 16777216
```

It didn't really seem right to set a queue size to a number as big as 16,777,216, but that solved the problem for us, and we didn't see any obvious adverse effects from setting the queue size so high. Do you know of a better way to size the queue?

**Comment by erasky** [comment]
Sorry, as a beginner,  I don't have a better way to size the queue.
