### ISSUE TITLE
Exception when calculating SBB skim matrices

### ISSUE THREAD

**Issue by markusstraub** [matsim-org/matsim-libs#2114]
This exception occurs during the skim matrix calculation **when parsing a facilities xml files that contain attributes**.

```
Exception in thread "main" java.lang.RuntimeException: Object is null; follow stack trace
        at org.matsim.core.gbl.Gbl.assertNotNull(Gbl.java:209)
        at org.matsim.utils.objectattributes.attributable.AttributesXmlReaderDelegate.endTag(AttributesXmlReaderDelegate.java:74)
        at org.matsim.facilities.FacilitiesReaderMatsimV1.endTag(FacilitiesReaderMatsimV1.java:132)
        at org.matsim.facilities.MatsimFacilitiesReader.endTag(MatsimFacilitiesReader.java:128)
        at org.matsim.core.utils.io.MatsimXmlParser.endElement(MatsimXmlParser.java:358)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
        at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLNSDTDValidator.endNamespaceScope(XMLNSDTDValidator.java:226)
        at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleEndElement(XMLDTDValidator.java:1934)
        at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.endElement(XMLDTDValidator.java:865)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1718)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2883)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:194)
        at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:149)
        at ch.sbb.matsim.analysis.skims.CalculateSkimMatrices.calculateSamplingPointsPerZoneFromFacilities(CalculateSkimMatrices.java:199)
```
An example facilities file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facilities SYSTEM "http://www.matsim.org/files/dtd/facilities_v1.dtd">
<facilities>
  <attributes>
    <attribute name="coordinateReferenceSystem" class="java.lang.String">epsg:31256</attribute>
  </attributes>
  ...
```

My fix was to replace ~~return null;~~ with `return new Attributes();` in [StreamingFacilities.java](https://github.com/matsim-org/matsim-libs/blob/43f4951f2e48c1a222457a32879e07d98e129166/contribs/sbb-extensions/src/main/java/ch/sbb/matsim/analysis/skims/StreamingFacilities.java#L65)

**Comment by jfbischoff** [comment]
Thanks for noting, I'll fix it on the master in the next couple of days :-)
