### ISSUE TITLE
socnetsim contrib: issues with JointTripMutator and pt

### ISSUE THREAD

**Issue by maprdhm** [matsim-org/matsim-libs#2255]
Hello,

I am trying to use the socnetsim contrib but I encounter 2 issues while running the example scenario.
I try to run _RunExampleSocialSimulation.java_ with files from the Sioux falls example, with Matsim version 15.0-SNAPSHOT.

The intput files, socnetsim code and outputs are here available here: [https://drive.google.com/drive/folders/10ff5JIWpaOEUDXlyl4ZLxXHkHHr0J7D3?usp=sharing](https://drive.google.com/drive/folders/10ff5JIWpaOEUDXlyl4ZLxXHkHHr0J7D3?usp=sharing)

1. The first issue (also referenced here: https://github.com/matsim-org/matsim-libs/issues/1094) appears when JointTripMutator is used as one of the strategies in the config file:

**Caused by: java.lang.RuntimeException: no valid trip found for passenger 10900_2 in driver trip**
Full error:
``
2022-10-26T14:34:10,168 ERROR AbstractMultithreadedGenericStrategyModule$ExceptionHandler:136 Thread SynchronizeCoTravelerPlansModule_1 died with exception. Will stop after all threads finished.
java.lang.RuntimeException: exception when handling JointPlan: plans=10900_2: 1; 7622_1: 1; 
	at org.matsim.contrib.socnetsim.framework.replanning.modules.AbstractMultithreadedGenericStrategyModule$PlanRunnable.run(AbstractMultithreadedGenericStrategyModule.java:124) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Problem analyzing joint plan JointPlan: plans=10900_2: 1; 7622_1: 1; 
	at org.matsim.contrib.socnetsim.jointtrips.JointTravelUtils.analyseJointTravel(JointTravelUtils.java:58) ~[classes/:?]
	at org.matsim.contrib.socnetsim.jointtrips.replanning.modules.SynchronizeCoTravelerPlansAlgorithm.run(SynchronizeCoTravelerPlansAlgorithm.java:64) ~[classes/:?]
	at org.matsim.contrib.socnetsim.jointtrips.replanning.modules.SynchronizeCoTravelerPlansAlgorithm.run(SynchronizeCoTravelerPlansAlgorithm.java:1) ~[classes/:?]
	at org.matsim.contrib.socnetsim.framework.replanning.modules.AbstractMultithreadedGenericStrategyModule$PlanRunnable.run(AbstractMultithreadedGenericStrategyModule.java:121) ~[classes/:?]
	... 1 more
Caused by: java.lang.RuntimeException: no valid trip found for passenger 10900_2 in driver trip [DriverTrip: driverId=7622_1, driverTrip=[leg [mode=car_driver][depTime=17:49:44][travTime=00:14:03][arrTime=18:03:48][route=[DriverRoute: delegate= startLinkId=18_4 endLinkId=29_3 travTime=OptionalTime[843.9259999999922] dist=7039.700908460415 linkIds=[55_1, 55_2, 55_3, 47_1, 47_2, 47_3, 47_4, 21_1, 21_2, 21_3, 21_4, 21_5, 25_1, 25_2, 29_1, 29_2] travelCost=0.2342696138046853; passengers=[10900_2]]]], passengerOrigins={10900_2=18_4}, passengerDestinations={10900_2=29_3}]
	at org.matsim.contrib.socnetsim.jointtrips.JointTravelUtils.getNextPassengerTrip(JointTravelUtils.java:122) ~[classes/:?]
	at org.matsim.contrib.socnetsim.jointtrips.JointTravelUtils.reconstructJointTrips(JointTravelUtils.java:75) ~[classes/:?]
	at org.matsim.contrib.socnetsim.jointtrips.JointTravelUtils.analyseJointTravel(JointTravelUtils.java:53) ~[classes/:?]
	at org.matsim.contrib.socnetsim.jointtrips.replanning.modules.SynchronizeCoTravelerPlansAlgorithm.run(SynchronizeCoTravelerPlansAlgorithm.java:64) ~[classes/:?]
	at org.matsim.contrib.socnetsim.jointtrips.replanning.modules.SynchronizeCoTravelerPlansAlgorithm.run(SynchronizeCoTravelerPlansAlgorithm.java:1) ~[classes/:?]
	at org.matsim.contrib.socnetsim.framework.replanning.modules.AbstractMultithreadedGenericStrategyModule$PlanRunnable.run(AbstractMultithreadedGenericStrategyModule.java:121) ~[classes/:?]
	... 1 more
``

2. The second issue (also mentionned here: https://github.com/matsim-org/matsim-code-examples/issues/66#issuecomment-763785537) appears when I try to add pt to the scenario (by switching useTransit to true in the config file):
**java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "org.matsim.core.mobsim.qsim.qnetsimengine.AbstractQNetsimEngine.getQnetsimEngineRunner()" is null**
Full issue:
``
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "org.matsim.core.mobsim.qsim.qnetsimengine.AbstractQNetsimEngine.getQnetsimEngineRunner()" is null
	at org.matsim.core.mobsim.qsim.qnetsimengine.AbstractQNetsimEngine.afterSim(AbstractQNetsimEngine.java:185) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.cleanupSim(QSim.java:357) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:269) ~[classes/:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:125) ~[classes/:?]
	at org.matsim.core.controler.AbstractController$9.run(AbstractController.java:212) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:244) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:208) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:155) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:122) ~[classes/:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82) ~[classes/:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:70) ~[classes/:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:53) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:90) ~[classes/:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:83) ~[classes/:?]
	at org.matsim.core.controler.Controler.run(Controler.java:250) ~[classes/:?]
	at org.matsim.contrib.socnetsim.examples.RunExampleSocialSimulation.main(RunExampleSocialSimulation.java:113) ~[classes/:?]
2022-10-26T14:38:57,747  WARN QSim:274 exception in finally block - this may be a follow-up exception of an exception thrown in the try block.
java.lang.RuntimeException: got exception while cleaning up the QSim. Please check the error messages above for details.
	at org.matsim.core.mobsim.qsim.QSim.cleanupSim(QSim.java:365) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:269) ~[classes/:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:125) ~[classes/:?]
	at org.matsim.core.controler.AbstractController$9.run(AbstractController.java:212) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:244) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:208) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:155) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:122) ~[classes/:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82) ~[classes/:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:70) ~[classes/:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:53) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:90) ~[classes/:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:83) ~[classes/:?]
	at org.matsim.core.controler.Controler.run(Controler.java:250) ~[classes/:?]
	at org.matsim.contrib.socnetsim.examples.RunExampleSocialSimulation.main(RunExampleSocialSimulation.java:113) ~[classes/:?]
``

Unfortunately I have not been able to find any example of the use of this contribution. Is the socnetsim contribution still maintained and used?
I am very interested in using it thus I would very much appreciate some guidance.

Thanks a lot!

**Comment by BhuminTechakul** [comment]
Hi has this been resolved? I have been running into the same issue.
2024-08-13T22:14:49,428 ERROR QSim:360 got exception while cleaning up
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "org.matsim.core.mobsim.qsim.qnetsimengine.AbstractQNetsimEngine.getQnetsimEngineRunner()" is null
	at org.matsim.core.mobsim.qsim.qnetsimengine.AbstractQNetsimEngine.afterSim(AbstractQNetsimEngine.java:184) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.QSim.cleanupSim(QSim.java:357) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:269) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:125) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:212) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:244) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:208) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:155) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:122) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:70) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:53) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:90) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.NewControler.run(NewControler.java:83) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.Controler.run(Controler.java:250) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.project.RunMatsim.main(RunMatsim.java:87) [MATSIM.jar:0.0.1-SNAPSHOT]
2024-08-13T22:14:49,477  WARN QSim:274 exception in finally block - this may be a follow-up exception of an exception thrown in the try block.
java.lang.RuntimeException: got exception while cleaning up the QSim. Please check the error messages above for details.
	at org.matsim.core.mobsim.qsim.QSim.cleanupSim(QSim.java:365) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:269) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:125) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:212) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:244) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:208) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:155) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:122) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:70) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:53) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:90) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.NewControler.run(NewControler.java:83) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.Controler.run(Controler.java:250) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.project.RunMatsim.main(RunMatsim.java:87) [MATSIM.jar:0.0.1-SNAPSHOT]
2024-08-13T22:14:49,477 ERROR AbstractController:223 Mobsim did not complete normally! afterMobsimListeners will be called anyway.
java.lang.RuntimeException: UmlaufId could not be found. veh=null
	at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:95) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.pt.ReconstructingUmlaufBuilder.build(ReconstructingUmlaufBuilder.java:82) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.getOrCreateUmlaufCache(TransitQSimEngine.java:149) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.createVehiclesAndDriversWithUmlaeufe(TransitQSimEngine.java:134) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.insertAgentsIntoMobsim(TransitQSimEngine.java:219) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.QSim.createAgents(QSim.java:309) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.QSim.prepareSim(QSim.java:294) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:242) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:125) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:212) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:244) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:208) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:155) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:122) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:70) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:53) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:90) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.NewControler.run(NewControler.java:83) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.Controler.run(Controler.java:250) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.project.RunMatsim.main(RunMatsim.java:87) [MATSIM.jar:0.0.1-SNAPSHOT]
2024-08-13T22:14:49,499 ERROR MatsimRuntimeModifications:76 Getting uncaught Exception in Thread main
java.lang.RuntimeException: UmlaufId could not be found. veh=null
	at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:95) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.pt.ReconstructingUmlaufBuilder.build(ReconstructingUmlaufBuilder.java:82) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.getOrCreateUmlaufCache(TransitQSimEngine.java:149) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.createVehiclesAndDriversWithUmlaeufe(TransitQSimEngine.java:134) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.insertAgentsIntoMobsim(TransitQSimEngine.java:219) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.QSim.createAgents(QSim.java:309) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.QSim.prepareSim(QSim.java:294) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:242) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:125) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:212) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:244) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:208) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:155) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:122) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:70) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:53) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:90) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.NewControler.run(NewControler.java:83) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.Controler.run(Controler.java:250) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.project.RunMatsim.main(RunMatsim.java:87) [MATSIM.jar:0.0.1-SNAPSHOT]
2024-08-13T22:14:49,500 ERROR MatsimRuntimeModifications:82 ERROR --- This is an unexpected shutdown!
2024-08-13T22:14:49,500 ERROR MatsimRuntimeModifications:85 Shutdown possibly caused by the following Exception:
java.lang.RuntimeException: UmlaufId could not be found. veh=null
	at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:95) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.pt.ReconstructingUmlaufBuilder.build(ReconstructingUmlaufBuilder.java:82) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.getOrCreateUmlaufCache(TransitQSimEngine.java:149) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.createVehiclesAndDriversWithUmlaeufe(TransitQSimEngine.java:134) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.insertAgentsIntoMobsim(TransitQSimEngine.java:219) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.QSim.createAgents(QSim.java:309) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.QSim.prepareSim(QSim.java:294) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:242) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:125) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:212) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:244) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:208) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:155) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:122) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82) ~[MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:70) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:53) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:90) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.NewControler.run(NewControler.java:83) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.core.controler.Controler.run(Controler.java:250) [MATSIM.jar:0.0.1-SNAPSHOT]
	at org.matsim.project.RunMatsim.main(RunMatsim.java:87) [MATSIM.jar:0.0.1-SNAPSHOT]
2024-08-13T22:14:49,646 ERROR MatsimRuntimeModifications:100 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2024-08-13T22:14:49,646 ERROR MatsimRuntimeModifications:101 ERROR --- results should not be used for further analysis.
2024-08-13T22:14:49,646 ERROR MatsimRuntimeModifications:105 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.RuntimeException: UmlaufId could not be found. veh=null
	at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:95)
	at org.matsim.pt.ReconstructingUmlaufBuilder.build(ReconstructingUmlaufBuilder.java:82)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.getOrCreateUmlaufCache(TransitQSimEngine.java:149)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.createVehiclesAndDriversWithUmlaeufe(TransitQSimEngine.java:134)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.insertAgentsIntoMobsim(TransitQSimEngine.java:219)
	at org.matsim.core.mobsim.qsim.QSim.createAgents(QSim.java:309)
	at org.matsim.core.mobsim.qsim.QSim.prepareSim(QSim.java:294)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:242)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:125)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:212)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:244)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:208)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:155)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:122)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:70)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:53)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:90)
	at org.matsim.core.controler.NewControler.run(NewControler.java:83)
	at org.matsim.core.controler.Controler.run(Controler.java:250)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:87)

The simulation did not run properly. Error/Exit code: 1

**Comment by mrieser** [comment]
@BhuminTechakul your question has nothing to do with socnetsim. Please create a new issue in the future.

I think the essential error message is:
> java.lang.RuntimeException: UmlaufId could not be found. veh=null
> at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:95) ~[MATSIM.jar:0.0.1-SNAPSHOT]

It seems as if your public transport schedule refers to a vehicle id that is not included in your transitVehicles.xml file, or that no vehicle ids are provided at all in your schedule. Have a look at https://github.com/matsim-org/matsim-code-examples/wiki/pt to learn how to properly model public transport in MATSim.
