### ISSUE TITLE
Matsim's emission contrib 

### ISSUE THREAD

**Issue by neda-git** [matsim-org/matsim-libs#2453]
Hello,
I would like to use matsim's emission contrib, I exported the hbefa data and converted to the csv, when I ran that I got the errors, could you please help me? thank you in advance.

Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
  at org.matsim.contrib.emissions.EmissionModule.<init>(EmissionModule.java:65)
  while locating org.matsim.contrib.emissions.EmissionModule

1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
	at org.eqasim.ile_de_france.emissions.RunComputeEmissionsEvents.main(RunComputeEmissionsEvents.java:72)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.matsim.contrib.emissions.HbefaTables.mapAmbientCondPattern2ParkingTime(HbefaTables.java:119)
	at org.matsim.contrib.emissions.HbefaTables.createColdKey(HbefaTables.java:80)
	at org.matsim.contrib.emissions.HbefaTables.load(HbefaTables.java:57)
	at org.matsim.contrib.emissions.HbefaTables.loadAverageCold(HbefaTables.java:38)
	at org.matsim.contrib.emissions.EmissionModule.createLookupTables(EmissionModule.java:144)
	at org.matsim.contrib.emissions.EmissionModule.<init>(EmissionModule.java:73)
	at org.matsim.contrib.emissions.EmissionModule$$FastClassByGuice$$3f5bb797.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
	... 2 more

**Comment by kainagel** [comment]
Dear neda-git, as usual difficult to tell without the full context.  I _think_ that the offending line is
```
        String parkingTimeString = string.split(",")[1];
```
If so, then after the split there is no element [1].  Either the string is empty, or it does not contain a comma.  This is called from
```
        key.setParkingTime(mapAmbientCondPattern2ParkingTime(record.get("AmbientCondPattern")));
```
So it looks like your `AmbientCondPattern` column is not there, or not filled, or does not contain a comma.

@rgraebe , could you please take note of this?  We need to provide better error messages if the input files contain mistakes.

**Comment by neda-git** [comment]
Dear @kainagel, Thank you for your response, as an example here is the header and some rows of my csv data:

EFA_ColdStart_Vehcat_2015_Cold_Average.csv

Case;VehCat;Year;TrafficScenario;Component;RoadCat;AmbientCondPattern;EFA_weighted;EFA_km_weighted;EFA_WTT_weighted;EFA_WTT_km_weighted;EFA_WTW_weighted;EFA_WTW_km_weighted

2015_Cold_Average[4.2.2];pass. car;2015;REF F HB42;HC;Urban;Ø/France - Avg;0,575411737;;;;;
2015_Cold_Average[4.2.2];pass. car;2015;REF F HB42;HC;Urban;Ø/France - Avg - spring;0,576464236;;;;;

EFA_ColdStart_Subsegm_2015_Cold_Detailed.csv

Case;VehCat;Year;TrafficScenario;Component;RoadCat;AmbientCondPattern;IDSubsegment;Subsegment;Technology;SizeClasse;EmConcept;KM;%OfSubsegment;EFA;EFA_weighted;EFA_km;EFA_km_weighted;EFA_WTT;EFA_WTT_km;EFA_WTW;EFA_WTW_km
2015_Cold_Detailed[4.2.2];pass. car;2015;REF F HB42;HC;Urban;Ø/France - Avg;111903;PC petrol ECE-15'03;petrol (4S);not specified;PC P Euro-0;212826,0313;7,67883E-05;7,009304523;0,575411737;;;;;;

EFA_HOT_Subsegm_2015_Hot_Detailed.csv

Case;VehCat;Year;TrafficScenario;Component;RoadCat;TrafficSit;Gradient;IDSubsegment;Subsegment;Technology;SizeClasse;EmConcept;KM;%OfSubsegment;V;V_0%;V_100%;EFA;EFA_0%;EFA_100%;V_weighted;V_weighted_0%;V_weighted_100%;EFA_weighted;EFA_weighted_0%;EFA_weighted_100%;AmbientCondPattern;EFA_WTT;EFA_WTT_0%;EFA_WTT_100%;EFA_WTW;EFA_WTW_0%;EFA_WTW_100%

2015_Hot_Detailed[4.2.2];pass. car;2020;;HC;;RUR/MW/80/Freeflow;0%;132932;PC CNG/petrol Euro-3_(P);bifuel CNG/petrol;not specified;PC CNG;50000;1;82,81607056;;;0,009782017;;;;;;;;;Ø/France - Avg;;;;;;

EFA_HOT_Vehcat_2015_Hot_Average.csv

2015_Hot_Average[4.2.2];pass. car;2015;REF F HB42 ;SO2 ;Urban ;URB/Access/50/St+Go2; 0%; 5,839002609; 0,00208513;Ø/France - Avg;;

2015_Hot_Average[4.2.2];HGV;2015;REF F HB42;HC;MW;RUR/MW/80/Freeflow;0%;81,29037476;0,066031165;;;


I've exported the data by following the steps of this link: https://www.matsim.org/apidocs/emissions/0.7.0/org/matsim/contrib/emissions/package-summary.html

My Hbefa version is 4.2.

I found some rows for AmbientCondPattern aren't filled, Do you think, I should select all patterns in COLD START EXCESS EMISSION FACTORS?

**Comment by neda-git** [comment]
I tried with:
 [sample_41_EFA_ColdStart_SubSegm_2020detailed.csv]
[sample_41_EFA_ColdStart_vehcat_2020average.csv]
[sample_41_EFA_HOT_HGV_2020detailed.csv]
[sample_41_EFA_HOT_SubSegm_2020detailed.csv]
[sample_41_EFA_HOT_vehcat_2020average.csv]

I got the different errors:

2023-03-22T14:10:16,457  INFO EventsManagerImpl:137  event # 1
2023-03-22T14:10:16,458  INFO EventsManagerImpl:137  event # 4
2023-03-22T14:10:16,458  INFO VehicleUtils:324 adding scenario element for allvehicles container
2023-03-22T14:10:16,458  INFO VehicleUtils:337 **vehicleId=177837 not in allVehicles; trying standard vehicles container ...**
2023-03-22T14:10:16,461  INFO ColdEmissionAnalysisModule:325 try reading detailed values
2023-03-22T14:10:16,461  INFO ColdEmissionAnalysisModule:326  This message given only once.
2023-03-22T14:10:16,461  INFO ColdEmissionAnalysisModule:327  Future occurences of this logging statement are suppressed.
2023-03-22T14:10:16,462  INFO ColdEmissionAnalysisModule:336 try to rewrite from HBEFA3 to HBEFA4 and lookup in detailed table again
2023-03-22T14:10:16,462  INFO ColdEmissionAnalysisModule:337  This message given only once.
2023-03-22T14:10:16,462  INFO ColdEmissionAnalysisModule:338  Future occurences of this logging statement are suppressed.
2023-03-22T14:10:16,468  **WARN ColdEmissionAnalysisModule:357 did not find emission factor for efkey=PASSENGER_CAR; PM; 13; 1; diesel; <1,4L; PC diesel Euro-3 (DPF)**
2023-03-22T14:10:16,468  WARN ColdEmissionAnalysisModule:358  re-written to PASSENGER_CAR; PM; 13; 1; diesel; average; average
2023-03-22T14:10:16,468  WARN ColdEmissionAnalysisModule:359 will try it with '<technology>; average; average'
2023-03-22T14:10:16,468  WARN ColdEmissionAnalysisModule:360  This message given only once.
2023-03-22T14:10:16,468  WARN ColdEmissionAnalysisModule:361  Future occurences of this logging statement are suppressed.
2023-03-22T14:10:16,469  INFO ColdEmissionAnalysisModule:325 try reading detailed values
2023-03-22T14:10:16,469  INFO ColdEmissionAnalysisModule:326  This message given only once.
2023-03-22T14:10:16,469  INFO ColdEmissionAnalysisModule:327  Future occurences of this logging statement are suppressed.
2023-03-22T14:10:16,469  INFO ColdEmissionAnalysisModule:336 try to rewrite from HBEFA3 to HBEFA4 and lookup in detailed table again
2023-03-22T14:10:16,469  INFO ColdEmissionAnalysisModule:337  This message given only once.
2023-03-22T14:10:16,469  INFO ColdEmissionAnalysisModule:338  Future occurences of this logging statement are suppressed.
2023-03-22T14:10:16,469  **WARN ColdEmissionAnalysisModule:357 did not find emission factor for efkey=PASSENGER_CAR; BC_exhaust; 13; 1; diesel; <1,4L; PC diesel Euro-3 (DPF)**
2023-03-22T14:10:16,469  WARN ColdEmissionAnalysisModule:358  re-written to PASSENGER_CAR; BC_exhaust; 13; 1; diesel; average; average
2023-03-22T14:10:16,469  WARN ColdEmissionAnalysisModule:359 will try it with '<technology>; average; average'
2023-03-22T14:10:16,469  WARN ColdEmissionAnalysisModule:360  This message given only once.
2023-03-22T14:10:16,469  WARN ColdEmissionAnalysisModule:361  Future occurences of this logging statement are suppressed.
2023-03-22T14:10:16,471  INFO WarmEmissionHandler:157 Vehicle 177837 is ending its first activity of the day and leaving link 32345 without having entered.
2023-03-22T14:10:16,472  INFO WarmEmissionHandler:158 This is because of the MATSim logic that there is no link enter event for the link of the first activity
2023-03-22T14:10:16,472  INFO WarmEmissionHandler:159 Thus, no emissions are calculated for this link leave event.
2023-03-22T14:10:16,472  INFO VehicleUtils:337 vehicleId=177837 not in allVehicles; trying standard vehicles container ...
2023-03-22T14:10:16,472  INFO VehicleUtils:337 vehicleId=177837 not in allVehicles; trying standard vehicles container ...
Exception in thread "main" java.lang.RuntimeException: At least the FREEFLOW condition must be specified for all emission factor keys. It was not found for PASSENGER_CAR; null; URB/Local/60; null; diesel; <1,4L; PC diesel Euro-3 (DPF)
	at org.matsim.contrib.emissions.WarmEmissionAnalysisModule.getTrafficSituation(WarmEmissionAnalysisModule.java:569)
	at org.matsim.contrib.emissions.WarmEmissionAnalysisModule.calculateWarmEmissions(WarmEmissionAnalysisModule.java:292)
	at org.matsim.contrib.emissions.WarmEmissionAnalysisModule.checkVehicleInfoAndCalculateWarmEmissions(WarmEmissionAnalysisModule.java:237)
	at org.matsim.contrib.emissions.WarmEmissionHandler.handleEvent(WarmEmissionHandler.java:219)
	at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:268)
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:141)
	at org.matsim.core.events.EventsReaderXMLv1.startEvent(EventsReaderXMLv1.java:104)
	at org.matsim.core.events.EventsReaderXMLv1.startTag(EventsReaderXMLv1.java:80)
	at org.matsim.core.events.MatsimEventsReader$XmlEventsReader.startTag(MatsimEventsReader.java:140)
	at org.matsim.core.utils.io.MatsimXmlParser.startElement(MatsimXmlParser.java:347)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:197)
	at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:149)
	at org.matsim.core.events.MatsimEventsReader.readFile(MatsimEventsReader.java:79)

**Comment by rgraebe** [comment]
Dear @neda-git, looking at your input data structure and specifically the contents of your `AmbientCondPattern` column for all of your different files, I picked up a few things. 

> here is the header and some rows of my csv data:
>
>EFA_ColdStart_Vehcat_2015_Cold_Average.csv
>
>Case;VehCat;Year;TrafficScenario;Component;RoadCat;AmbientCondPattern;EFA_weighted;EFA_km_weighted;EFA_WTT_weighted;EFA_WTT_km_weighted;EFA_WTW_weighted;EFA_WTW_km_weighted
>
>2015_Cold_Average[4.2.2];pass. car;2015;REF F HB42;HC;Urban;Ø/France - Avg;0,575411737;;;;;
>2015_Cold_Average[4.2.2];pass. car;2015;REF F HB42;HC;Urban;Ø/France - Avg - spring;0,576464236;;;;;

These are the two methods within [contrib/emissions/HbefaTables.java](https://github.com/matsim-org/matsim-libs/blob/master/contribs/emissions/src/main/java/org/matsim/contrib/emissions/HbefaTables.java) that use content read from the `AmbientCondPattern` column:

```
    private static int mapAmbientCondPattern2Distance(String string) {
        String distanceString = string.split(",")[2];
        String upperbound = distanceString.split("-")[1];
        return Integer.parseInt(upperbound.split("k")[0]);
    }

    private static int mapAmbientCondPattern2ParkingTime(String string) {

        String parkingTimeString = string.split(",")[1];
        if (parkingTimeString.equals(">12h")) {
            return 13;
        } else {
            String upperbound = parkingTimeString.split("-")[1];
            return Integer.parseInt(upperbound.split("h")[0]);
        }
    }
```

As you can see, these methods convert the string content to _parking time_ and _distance_, however, in none of your file examples are the relevant information to extract this data from. This tells me that something went wrong (or cannot yet be accommodated/inferred) with your export from HBEFA.

To answer this:
> Do you think, I should select all patterns in COLD START EXCESS EMISSION FACTORS?

The process, as you also mention from [contrib/emissions/package-summary.html](https://www.matsim.org/apidocs/emissions/0.7.0/org/matsim/contrib/emissions/package-summary.html) states that you should be selecting _"all "patterns" with average temperature, detailed parking time (0-1h .. >12h), and detailed distance (0-1km and 1-2km)"_. From what I know, this should probably not be something like _"Ø/France - Avg"_, which you have. Can you try to imitate the process to arrive at a csv file where you have these parking times and distances contained in your `AmbientCondPattern` column?

**Comment by rgraebe** [comment]
> I tried with:
> [sample_41_EFA_ColdStart_SubSegm_2020detailed.csv]
> [sample_41_EFA_ColdStart_vehcat_2020average.csv]
> [sample_41_EFA_HOT_SubSegm_2020detailed.csv]
> [sample_41_EFA_HOT_vehcat_2020average.csv]

@neda-git, to answer you about this, refer to the error:

> Exception in thread "main" java.lang.RuntimeException: At least the FREEFLOW condition must be specified for all emission factor keys. It was not found for PASSENGER_CAR; null; URB/Local/60; null; diesel; <1,4L; PC diesel Euro-3 (DPF)

This exception occurs when the hbefa file provided does not provide emission factors (a record in the hbefa csv file) for the specific vehicles in your scenario. Here, it started to look for the record with the `FREEFLOW` traffic condition, but couldn't find it. These "sample_41..." input files are small extracts from the more "complete" hbefa files (that you might need in your scenario), so it would make sense that they cause errors because they only serve a certain purpose in many test and example scenarios.

As a starting point, you can open `sample_41_EFA_HOT_vehcat_2020average.csv` and compare the contents with the record shown in the error _"PASSENGER_CAR; null; URB/Local/60; null; diesel; <1,4L; PC diesel Euro-3 (DPF)"_.  You will find that there is no `URB/Local/60` traffic situation for the passenger cars - once again, _because_ this is only a sample hbefa file... 

I hope this makes the origin of the error clear!

**Comment by neda-git** [comment]
Dear@rgraebe, Thank you for taking time to answer my questions, I will try to imitate the process to arrive at a csv file as you told me. I will come back to you soon. Ich danke dir.

**Comment by kt86** [comment]
The error points, that a consistency check of the hbefa tables says, that they are inconsistent:
![grafik](https://user-images.githubusercontent.com/12124568/228240229-8f1f619f-a35c-4c10-b82f-c9c2621fee2a.png)


In the emissionConfigGroup, you can set, what level of detail you prefer for the check:
e.g. in code by something like ...
`emissionsConfigGroup.setHbefaTableConsistencyCheckingLevel(EmissionsConfigGroup.HbefaTableConsistencyCheckingLevel.<....>);`
or in your config file.

Please see the corresponding comment for some more information:
https://github.com/matsim-org/matsim-libs/blob/df88413d1fdcce732284fa53dd6728b22ad0bd12/contribs/emissions/src/main/java/org/matsim/contrib/emissions/utils/EmissionsConfigGroup.java#L83-L88

@rgraebe : Maybe you (we) can also provide some more information in the Exception besides "inconsistent"? Thanks a lot.

**Comment by rgraebe** [comment]
> Caused by: java.lang.RuntimeException: inconsistent
> at org.matsim.contrib.emissions.WarmEmissionAnalysisModule.(WarmEmissionAnalysisModule.java:171)

@neda-git, related to this part in your error stack trace, I can advise you on the following:

There is a consistency check in the `WarmEmissionAnalysisModule` that checks the consistency of your _detailed hbefa file_ (i.e. `./EFA_HOT_Subsegm_2015_hot_detailed.csv` for you). This consistency check looks like this (extracted from `WarmEmissionAnalysisModule`):

```
// ... the thing to check would be if for each existing
//  roadCategory x vehicleCategory x vehicleAttribute x pollutant
// there is a freeflow and a stopgo entry.  Maybe something like this here:
Set<String> freeflowSet = new HashSet<>();
Set<String> stopgoSet = new HashSet<>();
for (HbefaWarmEmissionFactorKey key : detailedHbefaWarmTable.keySet()) {
String syntheticKey = key.getRoadCategory() + "--" + key.getVehicleCategory() + "--" + key.getVehicleAttributes() + "--" + key.getComponent();
switch ( key.getTrafficSituation() ) {
	case FREEFLOW -> freeflowSet.add( syntheticKey );
	case STOPANDGO -> stopgoSet.add( syntheticKey );
	default -> { } // do nothing
}
}
for (String syntheticKey : freeflowSet) {
if (!stopgoSet.contains(syntheticKey)) {
	throw new RuntimeException("inconsistent");
}
}
for (String syntheticKey : stopgoSet) {
if (!freeflowSet.contains(syntheticKey)) {
	throw new RuntimeException("inconsistent");
}
}
```

Your error creeps in here:
> at org.matsim.contrib.emissions.WarmEmissionAnalysisModule.(WarmEmissionAnalysisModule.java:171)

... at line 171. In the code extract, this is here:

> for (String syntheticKey : stopgoSet) {
> if (!freeflowSet.contains(syntheticKey)) {
> 	throw new RuntimeException("inconsistent");
> }

meaning that within your detailed hbefa file, for some roadCategory x vehicleCategory x vehicleAttribute x pollutant combination, there is a **freeflow** entry missing. 
I would also start troubleshooting here...

**Comment by neda-git** [comment]
Thanks Dear @rgraebe, It's clear now.

**Comment by neda-git** [comment]
Dear all, I got the following error, I checked my hbefa hot detailed and the other csv data, but I didn't find any problem in my csv, I checked it for finding the extra semicolon, any space etc but i didn't find any anomaly related to this error:

java.lang.IllegalArgumentException: Index for header 'Component' is 4 but CSVRecord only has 1 values!
	at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:129)
	at org.matsim.contrib.emissions.HbefaTables.setCommonParametersOnKey(HbefaTables.java:88)
	at org.matsim.contrib.emissions.HbefaTables.createWarmKey(HbefaTables.java:69)
	at org.matsim.contrib.emissions.HbefaTables.lambda$loadDetailedWarm$1(HbefaTables.java:31)
	at org.matsim.contrib.emissions.HbefaTables.load(HbefaTables.java:57)
	at org.matsim.contrib.emissions.HbefaTables.loadDetailedWarm(HbefaTables.java:30)
	at org.matsim.contrib.emissions.EmissionModule.createLookupTables(EmissionModule.java:152)
	at org.matsim.contrib.emissions.EmissionModule.<init>(EmissionModule.java:73)
	at org.matsim.contrib.emissions.EmissionModule$$FastClassByGuice$$3f5bb797.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
	... 2 more

![Screenshot from 2023-03-31 13-04-46](https://user-images.githubusercontent.com/79261451/229103965-727399c3-a6b0-41fa-8256-a7351f4b74a5.png)

**Comment by neda-git** [comment]
Hello @rgraebe , @kainagel , @kt86, I would like to say thank you for your help, I have successfully finished it. Now, I have emissions events file.

**Comment by kainagel** [comment]
Glad to hear that.
