### ISSUE TITLE
Dependency to GTFS2MATSim 14.0 with different groupId?

### ISSUE THREAD

**Issue by marecabo** [matsim-org/matsim-libs#2501]
Are `com.github.matsim-org:gtfs2matsim` and `org.matsim.contrib:matsim-gtfs` the same thing?

https://github.com/matsim-org/matsim-libs/blob/dbbd71fa8eea00d88ce46dee11c0f403a0b21939/contribs/application/pom.xml#L68-L71

https://github.com/matsim-org/GTFS2MATSim/blob/master/pom.xml#L4-L6
```xml
	<groupId>org.matsim.contrib</groupId>
	<artifactId>matsim-gtfs</artifactId>
	<version>15.0-SNAPSHOT</version>
```

I am asking, as I cannot find `com.github.matsim-org` in the official MATSim Maven repo (https://repo.matsim.org/repository/matsim) and the `application` contrib is refering to a hard-coded `14.0` version.

@rakow I think, you worked in both places, could you add some comment maybe? Thanks a lot in advance!

**Comment by marecabo** [comment]
`CreateTransitScheduleFromGtfs` fails because of this old version. This stayed unnoticed because it has no test.

```log
...
2023-04-11T13:35:42,031  INFO GTFSFeed:188 0 errors
2023-04-11T13:35:42,336  INFO GtfsConverter:86 Earliest date mentioned in feed: 2022-09-19
2023-04-11T13:35:42,337  INFO GtfsConverter:102 Latest date mentioned in feed: 2022-09-26
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface org.matsim.utils.objectattributes.attributable.Attributes, but class was expected
        at org.matsim.contrib.gtfs.GtfsConverter.convert(GtfsConverter.java:103)
        at org.matsim.application.prepare.pt.CreateTransitScheduleFromGtfs.call(CreateTransitScheduleFromGtfs.java:132)
        at org.matsim.application.prepare.pt.CreateTransitScheduleFromGtfs.call(CreateTransitScheduleFromGtfs.java:1)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.matsim.application.prepare.pt.CreateTransitScheduleFromGtfs.main(CreateTransitScheduleFromGtfs.java:93)
```

**Comment by rakow** [comment]
This converter can be found here https://github.com/matsim-org/GTFS2MATSim, it is not the same as matsim-gtfs.

It is unfortunately only available on jitpack and because it is in a different repository, it is not easy to keep in sync. There is a circular dependency between the two. It would probably be better if it would be a contrib as well.

Anyway, there is a version fixes the issues you mentioned, I will update it today or tomorrow.

**Comment by marecabo** [comment]
Great thanks for getting back and having a look. I am still a bit confused though: 

The pom in https://github.com/matsim-org/GTFS2MATSim provides the artifact `org.matsim.contrib:`**matsim-gtfs**, and the resulting jar is deployed to another repo under the name `com.github.matsim-org:`**gtfs2matsim**?

If they are not the same (=providing the same functinality under the same imports) could you point me to the codebase of `com.github.matsim-org:gtfs2matsim`?

**Comment by rakow** [comment]
The repo you mentioned is the correct one. When jitpack builds the package, it overwrites what is written in the pom.xml. `com.github.matsim-org:gtfs2matsim` is the name where it is currently deployed automatically. 

I see that there is a `org.matsim.contrib:matsim-gtfs` in the matsim repo with version 0.8.0, but I don't know where that comes from. Maybe it is a really old version of the same thing, but there is no setup to deploy it to the official repo currently.

**Comment by markusstraub** [comment]
Just adding a note if somebody stumbles on build failures like this:

> [ERROR] Failed to execute goal on project matsim-salabim: Could not resolve dependencies for project at.ac.ait:matsim-salabim:jar:2025.0-SNAPSHOT: Failed to collect dependencies at org.matsim.contrib:drt-extensions:jar:2025.0-PR3544 -> org.matsim.contrib:informed-mode-choice:jar:2025.0-PR3544 -> org.matsim.contrib:application:jar:2025.0-PR3544 -> com.github.matsim-org:gtfs2matsim:jar:19f1676fc6: Failed to read artifact descriptor for com.github.matsim-org:gtfs2matsim:jar:19f1676fc6: **Could not transfer artifact com.github.matsim-org:gtfs2matsim:pom:19f1676fc6** from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [ait.nexus (http://nexus.ait.ac.at:8081/content/groups/maven-public/, default, releases+snapshots)] -> [Help 1]

1. add the jitpack.io repo to your pom.xml (see https://github.com/matsim-org/matsim-libs/blob/master/contribs/application/pom.xml)
2. if it still doesn't work maybe jitpack is down (https://statusgator.com/services/jitpack)
