### ISSUE TITLE
MatsimXmlParser exception

### ISSUE THREAD

**Issue by nimra98** [matsim-org/matsim-libs#2934]
Hey,
I'm an unexperienced MATSim user and currently running into issues when trying to validate a transit-schedule using the integrated GUI function.
```2023-11-15T16:25:29,024  INFO Config:602 setting context to [file:/XXXXXXX]
2023-11-15T16:25:29,140  INFO Version:21 HV000001: Hibernate Validator 8.0.0.Final
2023-11-15T16:25:29,483  INFO MatsimXmlParser:148 starting to parse xml from file  ...
2023-11-15T16:25:29,497  INFO IOUtils:231 Resolved  to file:/XXXXXXX/target/classes/
null
null
null
Content is not allowed in prolog.
Content is not allowed in prolog.
XML-FATAL: , line 1, column 1:
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
Exception in thread "Thread-0" org.matsim.core.utils.io.UncheckedIOException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:205)
	at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:150)
	at org.matsim.run.gui.ScheduleValidatorWindow.lambda$run$4(ScheduleValidatorWindow.java:171)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:199)
	... 3 more
```

This happens when using the executable GUI from the example-project with the following schedule file:

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE transitSchedule SYSTEM "http://www.matsim.org/files/dtd/transitSchedule_v1.dtd">
<transitSchedule>
    <transitStops>
        <stopFacility id="1a" x="6020870.1844935" y="573623.4328989" linkRefId="100-1"/>
        <stopFacility id="1b" x="6020870.1844935" y="573623.4328989" linkRefId="2-1" />
        <stopFacility id="2a" x="6021190.4138405" y="573660.681021" linkRefId="1-2" />
        <stopFacility id="2b" x="6021190.4138405" y="573660.681021" linkRefId="3-2" />
        <stopFacility id="3a" x="6021479.1054488" y="573693.1145062" linkRefId="2-3" />
        <stopFacility id="3b" x="6021479.1054488" y="573693.1145062" linkRefId="4-3" />
        <stopFacility id="4a" x="6021783.1366797" y="573707.2225474" linkRefId="3-4" />
        <stopFacility id="4b" x="6021783.1366797" y="573707.2225474" linkRefId="5-4" />
        <stopFacility id="5a" x="6022168.7556627" y="573684.8287398" linkRefId="4-5" />
        <stopFacility id="5b" x="6022168.7556627" y="573684.8287398" linkRefId="6-5" />
        <stopFacility id="6a" x="6022574.9766665" y="573654.8212345" linkRefId="5-6" />
        <stopFacility id="6b" x="6022574.9766665" y="573654.8212345" linkRefId="7-6" />
        <stopFacility id="7" x="6022950.1451276" y="573619.887124" linkRefId="6-7" />
        <stopFacility id="8" x="6023021.2076773" y="573591.8204026" linkRefId="10-8" />
        <stopFacility id="9" x="6023672.5647688" y="573491.4966537" linkRefId="7-9" />
        <stopFacility id="10" x="6023552.83333" y="573501.3498644" linkRefId="12-10" />
        <stopFacility id="11" x="6023990.7038916" y="573469.2524335" linkRefId="9-11" />
        <stopFacility id="12" x="6023897.8448455" y="573450.4417585" linkRefId="13-12" />
        <stopFacility id="13a" x="6024260.4728566" y="573499.5585208" linkRefId="11-13" />
        <stopFacility id="13b" x="6024260.4728566" y="573499.5585208" linkRefId="14-13" />
        <stopFacility id="14a" x="6024802.997056" y="573489.7048623" linkRefId="13-14" />
    </transitStops>
    <transitLine id="Line Two">
        <transitRoute id="HZ12-HN9">
            <description>Teillinie 2 Dreiecksplatz bis Wik</description>
            <transportMode>tram</transportMode>
            <routeProfile>
                <stop refId="1a" departureOffset="00:00:00" />
                <stop refId="2a" arrivalOffset="00:00:50" departureOffset="00:01:13" />
                <stop refId="3a" arrivalOffset="00:01:59" departureOffset="00:02:19" />
                <stop refId="4a" arrivalOffset="00:03:02" departureOffset="00:03:24" />
                <stop refId="5a" arrivalOffset="00:04:20" departureOffset="00:04:42" />
                <stop refId="6a" arrivalOffset="00:05:28" departureOffset="00:05:47" />
                <stop refId="7" arrivalOffset="00:06:32" departureOffset="00:06:52" />
                <stop refId="9" arrivalOffset="00:08:02" departureOffset="00:08:22" />
                <stop refId="11" arrivalOffset="00:09:11" departureOffset="00:09:32" />
                <stop refId="13a" arrivalOffset="00:10:24" departureOffset="00:10:45" />
                <stop refId="14a" arrivalOffset="00:12:27" />
            </routeProfile>
            <route>
                <link refId="100-1" />
                <link refId="1-2" />
                <link refId="2-3" />
                <link refId="3-4" />
                <link refId="4-5" />
                <link refId="5-6" />
                <link refId="6-7" />
                <link refId="7-9" />
                <link refId="9-11" />
                <link refId="11-13" />
                <link refId="13-14" />
            </route>
            <departures>
                <departure id="01" departureTime="06:00:00" vehicleRefId="tram1" />
                <departure id="02" departureTime="06:10:00" vehicleRefId="tram2" />
                <departure id="03" departureTime="06:20:00" vehicleRefId="tram3" />
            </departures>
        </transitRoute>
    </transitLine>
</transitSchedule>
```

Interestingly this file seems to break something deep down.
When I use the simple example (https://github.com/matsim-org/matsim-libs/blob/master/examples/scenarios/pt-simple/transitschedule.xml) on a freshly cloned example project, everything works fine.
But after the first try (and fail) with my own file, even this "original" file won't work anymore and lead to the same error.
I can't spot an error in the beginning of the file itself in a HEX editor (which seems to be a common issue for this type of error):
![grafik](https://github.com/matsim-org/matsim-libs/assets/6324350/d56acc37-e959-4cbd-a376-d4dfecddcd5a)

Any hint would be greatly appreciated.

Running eclipse 2023-09 on Windows 10:
![grafik](https://github.com/matsim-org/matsim-libs/assets/6324350/a7dcd642-6a26-4d2e-8038-47038be3a958)

**Comment by nimra98** [comment]
This issue seems to persist on a fresh Ubuntu VM as well.
When starting the pt-simple simulation, the following logs are generated:
[logfile.log](https://github.com/matsim-org/matsim-libs/files/13377049/logfile.log)
[logfileWarningsErrors.log](https://github.com/matsim-org/matsim-libs/files/13377050/logfileWarningsErrors.log)

**Comment by mrieser** [comment]
In the last logfile, there is a different error message:

```
java.lang.RuntimeException: Unmaterialized config group: controller
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:32) ~[matsim-15.0.jar:?]
	at org.matsim.core.config.Config.checkConsistency(Config.java:240) ~[matsim-15.0.jar:?]
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:87) ~[matsim-15.0.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80) ~[matsim-15.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:70) [matsim-15.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:53) [matsim-15.0.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:90) [matsim-15.0.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:83) [matsim-15.0.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:250) [matsim-15.0.jar:?]
	at org.matsim.project.RunMatsim.main(RunMatsim.java:87) [classes/:?]
```

Up to a few weeks ago, including MATSim 15.0, it was wrongly spelled as `controler` (only a single `l`).

**Comment by nimra98** [comment]
@mrieser Thanks for the hint, I will have a look into this in the next week.
